### ISSUE TITLE
Directing adapter output away from REPL

### ISSUE THREAD

**Issue by richchurcher** [mrcjkb/rustaceanvim#113]
I don't think this is actually our problem, _per se_... it appears to be `lldb-dap` behaviour. But do you perhaps have thoughts on how we could overcome this situation? Output goes straight to REPL instead of console, which wouldn't be a problem except that the REPL doesn't grok ANSI colour codes:

![ansi](https://github.com/mrcjkb/rustaceanvim/assets/171905/f332f46a-f981-4f9d-9dae-c44c71e3bccb)
 
I don't suppose there's a way we could invoke the adapter that points its stdio elsewhere? I know in other adapters you can do `console = 'integratedTerminal'` but I haven't had any luck with that and suspect they don't support it.

**Comment by mrcjkb** [comment]
🤔 I don't use dap often enough for it to have been an issue for me.
If redirecting stdout doesn't work, maybe adding the [`--no-use-colors`](https://lldb.llvm.org/man/lldb.html#cmdoption-lldb-no-use-colors) flag will help?

Something along the lines of

```lua
dap.configurations.rust = {
  -- <...>
  args = { '--no-use-colors' },
}
```

**Comment by richchurcher** [comment]
Yeah there's all kinds of questions here. It's definitely not an issue for this plugin (yet) so closing. I checked in with `nvim-dap` to see if I can get more details about how adaptors should send output (apparently, all `OutputEvent`s get sent to the REPL by default). I may have to wait until llvm 17 lands in Arch before I can do much more.

**Comment by mrcjkb** [comment]
Not sure if it's relevant to `lldb-dap`, but maybe [`stdio` redirection is helpful for `codelldb`](https://github.com/vadimcn/codelldb/blob/v1.9.0/MANUAL.md#stdio-redirection)?
