### ISSUE TITLE
Any intention/plan for using `vim.api` for most/all your features?

### ISSUE THREAD

**Issue by ChocolateOverflow** [mrcjkb/rustaceanvim#128]
### Feature description

I use multiple languages and would like to keep a single set of key bindings for all my LSP stuff. Most of my bindings currently use `vim.lsp` and I'd rather not have `rustaceanvim` be a major outlier. (Of course, stuff not in the standard `vim.lsp` features will probably have to stay separate, I just wanna avoid duplicates & clashes.)
Will you make most/all of `rustaceanvim`'s features available via the `vim.lsp` API?

**Comment by mrcjkb** [comment]
Hey 👋 

`vim.lsp` is a built-in neovim runtime module.
I'd prefer not to "hack into" that, because:

a) it's an additional API to maintain
b) it could lead to unexpected behaviour, because I don't own the module.

Standard features, like hover actions, should already be available via `vim.lsp`.

**Comment by trevarj** [comment]
@ChocolateOverflow you can factor out the lsp `on_attach` keybindings that are used in `nvim-lspconfig` and initialize them on `on_attach` in both `nvim-lspconfig` and `rustaceanvim`:

Keep in mind that rust-analyzer has non-standard LSP functions that will not be applicable to other LSPs...

Within `nvim-lspconfig` config using lazy.nvim:
```lua
vim.api.nvim_create_autocmd("LspAttach", {
  callback = function(args)
  vim.lsp.inlay_hint.enable()
  cmd([[autocmd BufWritePre * lua vim.lsp.buf.format()]])
  config.keymaps").lsp_attach(args.buf) -- <--- here
end,
})
```

Within `rustaceanvim`'s `on_attach` field:

```lua
on_attach = function(_, bufnr)
  vim.lsp.inlay_hint.enable(bufnr)
  require("config.keymaps").lsp_attach(bufnr) -- <--- and here
end
```

Where the `lsp_attach` function is doing all the mappings:
```lua
function M.lsp_attach(buffer)
  local lsp = vim.lsp.buf
  map("n", "<leader>ca", lsp.code_action, "Code Action")
  -- truncated, just add whatever else you want
end

```
