### ISSUE TITLE
Codelldb couldn't connect

### ISSUE THREAD

**Issue by Gremious** [mrcjkb/rustaceanvim#129]
### Neovim version (nvim -v)

v0.9.4

### Operating system/version

Windows 11 22631.2861

### Output of :checkhealth rustaceanvim

```console
1 ──────────────────────────────────────────────────────────────────────────────
  2 rustaceanvim: require("rustaceanvim.health").check()
  3
  4 Checking for Lua dependencies
  5 - OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.
  6
  7 Checking external dependencies
  8 - OK rust-analyzer: found
  9 - OK Cargo: found
 10 - OK rustc: found
 11 - OK debug adapter: found codelldb
 12
 13 Checking config
 14 - OK No errors found in config.
 15
 16 Checking for conflicting plugins
 17 - OK No conflicting plugins detected.
 18
```

### How to reproduce the issue

```console
Run `:RustLsp debuggables` on a basic hello world bin.
```

### Expected behaviour

It debugs.

### Actual behaviour

```
C:\Users\Username\AppData\Local\nvim-data\mason\packages\codelldb/extension/adapter/codelldb.exe exited with code 101
Couldn't connect to 127.0.0.1:${port}: ECONNREFUSED
```

Not sure if this is maybe a codelldb or nvim-dap or mason issues sorry, may not be the right place to ask.

But googling it just vaguely tells me "Make sure the path to your LLDB is correct" which rustaceanvim told me it'll handle by itself and just find it from mason.

### The minimal config used to reproduce this issue.

```Lua
Sorry too sleepy, I just installed codelldb via mason and then that's it. No configured nvim-dap or rustacean dap settings, just defaults.
```

**Comment by mrcjkb** [comment]
Hey 👋 

The error message shows that rustaceanvim has correctly picked up the path from mason.
This looks like a codelldb issue, likely related to https://github.com/vadimcn/codelldb/issues/57

**Comment by Gremious** [comment]
Leaving an answer for anyone else stumbling upon this - I had just never properly configured nvim-dap as per [their docs](https://github.com/mfussenegger/nvim-dap/wiki/C-C---Rust-(via--codelldb)).

The port was never set, and you have to actually make it launch the adapter (or run it from the console yourself), so now that it looks like this it works:

```lua
{
	"mfussenegger/nvim-dap",
	config = function()
		require("dap").adapters.lldb = {
			type = 'server',
			host = '127.0.0.1',
			port = 13000,
			executable = {
				command = vim.fn.stdpath("data") .. "/mason/packages/codelldb/extension/adapter/codelldb",
				args = {"--port", "13000"},

				-- on windows you may have to uncomment this:
				-- detached = false,
			},
		}
	end,
},
```

**Comment by FredericRuaudel** [comment]
Thanks @Gremious for your comments, it gives me enough clue to fix another issue on macOS which is gatekeeper related.

I tried to run in the terminal the command `/path/to/extension/adapter/codelldb --port 13000` and get an mac alert popup saying that the executable wasn't correctly signed and thus can't be run.
To fix this, you need to follow these 3 steps:
1. open `/path/to/extension/lldb/lib/liblldb.dylib` **in Finder** and **right-click->Open** it (don't double click it), accept the alert and it will run it in the terminal. Close the terminal
2. open `/path/to/extension/lldb/lib/libpython39.dylib`  **in Finder** and do the same
3. finally, open `/path/to/extension/adapter/codelldb` **in Finder** and do the same again

Now you should be able to run `/path/to/extension/adapter/codelldb --port 13000` in the terminal without any issue.
