### ISSUE TITLE
To add a border to the "explainError" floating window

### ISSUE THREAD

**Issue by saying121** [mrcjkb/rustaceanvim#132]
### Feature description

It is difficult to differentiate the explainError floating window at the moment.

**Comment by mrcjkb** [comment]
Should be doable in the same way it's done for hover actions.

Maybe the config can be extracted to something shared between the two.

I'm away until January 12, but in the meantime, PRs are welcome 😄

**Comment by mrcjkb** [comment]
Closed by #133
