### ISSUE TITLE
Add example rust-analyzer.json file

### ISSUE THREAD

**Issue by Madoshakalaka** [mrcjkb/rustaceanvim#136]
### Feature description

I couldn't get the project local rust-analyzer.json file to work. Here is my file, which only intends to add the `foo` feature:

```json
{
    "check": {
        "features": [
            "foo"
        ]
    },
    "cargo": {
        "features": [
            "foo"
        ]
    }
}
```

I must have gotten the format run? But it's so silent, maybe output a warning when parsing fails?

**Comment by mrcjkb** [comment]
Hey :wave: 

I don't think this plugin has failed to parse the JSON. It just doesn't match the schema expected by rust-analyzer, and rust-analyzer is silent. So I think this would be an upstream (rust-analyzer) issue.

I'm afraid there's no way for this plugin to validate the schema, as rust-analyzer doesn't provide a CLI to do so.

To fix your config, please refer to

- The [rust-analyzer manual](https://rust-analyzer.github.io/manual.html#configuration)
- [This example](https://github.com/rust-analyzer/rust-project.json-example/blob/master/.vscode/settings.json).

From my  side, the most I can do is link to the example in the readme.

**Comment by mrcjkb** [comment]
Fixed in https://github.com/mrcjkb/rustaceanvim/commit/c685e323f97826889389e0c1fe7cbef03066d254

**Comment by Madoshakalaka** [comment]
to those confused, I finally got it working. To activate all features for example, you have to have this format in the `rust-analyzer.json`:
```json
{
    "rust-analyzer": {
        "cargo": {
            "features": "all"
        }
    }
}
```

**Comment by cosmikwolf** [comment]
I actually had a different experience, not sure if something has changed since you validated it @Madoshakalaka 

this is the `rust-analyzer.json` that worked for me
```
{
  "check": {
    "command": "clippy
  },
}
```

I was able to validate that it was being processed by setting `RA_LOG="rust_analyzer=debug"` and using `RustLsp logFile` to see that it actually was able to properly deserialize the configuration. It would not properly deserialize with a `rust-analyzer` main element.

**Comment by mrcjkb** [comment]
@cosmikwolf thanks for pointing this out. That was due to a bug fix that accidentally broke compatibility with @Madoshakalaka's format.
I have pushed a fix, and now it works with both schemas (by first checking for a `"rust-analyzer"` key and adding everything if there is none).
