### ISSUE TITLE
backport inlay_hints parameter_hints_prefix and other_hints_prefix from rust-tools

### ISSUE THREAD

**Issue by gbin** [mrcjkb/rustaceanvim#137]
### Feature description

see https://github.com/simrat39/rust-tools.nvim/commit/99a618f6955930e24f9e9306f4289385fc9febb8

Today it looks like the inlays don't have any prefix:
![image](https://github.com/mrcjkb/rustaceanvim/assets/975564/02e1637a-9d0f-46f0-aeaa-a765898798f1)

**Comment by mrcjkb** [comment]
Hey 👋 

To do so, I would have to re-add the custom inlay hints feature, which doesn't make sense to me, now that neovim is getting built-in inlay hints.
