### ISSUE TITLE
Better nvim-dap integration

### ISSUE THREAD

**Issue by paulkre** [mrcjkb/rustaceanvim#145]
### Feature description

Currently, it is possible to start a DAP debug session by running `RustLsp debuggables`. It would be great though if you could also use the default way of launching debug sessions by running `require("dap").continue()`. This would require that this plugin registers the debuggables directly inside nvim-dap before `require("dap").continue()` is called.

Here is how [nvim-jdtls](https://github.com/mfussenegger/nvim-jdtls) achieves this:

```lua
require("jdtls.dap").setup_dap_main_class_configs {
  on_ready = function() require("dap").continue() end,
}
```

It would be amazing if rustaceanvim could also expose some function like `setup_dap_main_class_configs`.

**Comment by mrcjkb** [comment]
It kind of works.

Sometimes it doesn't seem to load the configurations on the first startup (but it does when reopening the file).
I think this is likely because rust-analyzer takes a very long time to initialize...
