### ISSUE TITLE
Structural Search and Replace (SSR) just for selected range

### ISSUE THREAD

**Issue by Logarithmus** [mrcjkb/rustaceanvim#150]
### Feature description

Hello. I would like to be able to run SSR not for entire workspace, but just a single file, or, preferably, neovim selection. Is it possible?

**Comment by mrcjkb** [comment]
Hey :wave:

Based on the rust-analyzer documentation, that should be possible.
I'll look into it.

Thanks for requesting 🙏

**Comment by mrcjkb** [comment]
I've played around with this (see #160), but couldn't get it working yet.
Going to have to put this on hold...
