### ISSUE TITLE
[Windows] rustaceanvim spawns many instances of RustAnalyzer

### ISSUE THREAD

**Issue by TrungNguyen153** [mrcjkb/rustaceanvim#151]
### Neovim version (nvim -v)

0.9.5-> nightly 0.10.xx

### Operating system/version

Windows

### Output of :checkhealth rustaceanvim

```console
==============================================================================
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 0.3.1791-standalone (9db515503 2024-01-01)
- OK Cargo: found 
- OK rustc: found 
- OK debug adapter: found codelldb 

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.
```

### How to reproduce the issue

```console
.
```

### Expected behaviour

Only spawn 1 instance RustAnalyzer on root_dir project

### Actual behaviour

By some how plugin spawn 2 RustAnalyzer instance on same root because vim.lsp.start(lsp_options).
It spawn 2 kind of this path:
root directory:  D:\rust-workspace\same-project-a
root directory:  d:\rust-workspace\same-project-a
yes. difference is D vs d => vim.lsp.start spawn 2 instance on same-project-a

### The minimal config used to reproduce this issue.

```Lua
.
```

**Comment by TrungNguyen153** [comment]
seem vim.api.nvim_buf_get_name return difference Case sensive for file in root dir

**Comment by TrungNguyen153** [comment]
fast fix is:
  local function normalize_path(path)
    local has_windows_drive_letter = path:match '^%a:'
    if has_windows_drive_letter then
      return path:sub(1,1):lower()..path:sub(2)
    end
    return path
  end
  lsp_start_opts.root_dir = normalize_path(root_dir)


  https://github.com/mrcjkb/rustaceanvim/blob/master/lua/rustaceanvim/lsp.lua#L108C3-L108C37

**Comment by mrcjkb** [comment]
Thanks for the detailed report 🙏
