### ISSUE TITLE
Native inlay hints are not drawn correct when server starts for nvim 10

### ISSUE THREAD

**Issue by snaggen** [mrcjkb/rustaceanvim#155]
### Neovim version (nvim -v)

v.0.10.0

### Operating system/version

Fedora Linux 39

### Output of :checkhealth rustaceanvim

```console
On my phone, not available and not relevant.
```

### How to reproduce the issue

```console
Enable native inlay hints, open rust file. 

Details in this bug report, consensus there is that this workaround should be in rustaceanvim.

https://github.com/neovim/neovim/issues/26511#issuecomment-1890962251
```

### Expected behaviour

Inlay hints should be visible 

### Actual behaviour

Inlay hints are not shown

### The minimal config used to reproduce this issue.

```Lua
Not available
```

**Comment by snaggen** [comment]
Enable native inlay hints, open rust file. 

Details in this bug report, consensus there is that this workaround should be in rustaceanvim.

https://github.com/neovim/neovim/issues/26511#issuecomment-1890962251

**Comment by mrcjkb** [comment]
Hey :wave: 

thanks for reporting. Should be an easy fix :smile:

**Comment by mrcjkb** [comment]
Will address some more issues and then tag a new release.
