### ISSUE TITLE
Focused window is lost after secondary float opens

### ISSUE THREAD

**Issue by aikixd** [mrcjkb/rustaceanvim#169]
### Neovim version (nvim -v)

0.10.0

### Operating system/version

ubuntu 22.04

### Output of :checkhealth rustaceanvim

```console
---
```

### How to reproduce the issue

```console
Have two or more windows opened. Open code action in a non-leftmost window. Enter secondary float and close it ('q' or '<cr>').
```

### Expected behaviour

Cursor to return to the window in which code action was invoked.

### Actual behaviour

Cursor is returned to the leftmost window.

NB: I've made a temporary fix for myself by tracking the current window:
`M.state.cur_win = vim.api.nvim_get_current_win()` in `on_code_action_results`
`vim.api.nvim_set_current_win(M.state.cur_win)` in `cleanup`

My guess is that on window close, nvim moves caret to 'other' window. Since 2 are closed, there is no other window to use and the leftmost is chosen.

### The minimal config used to reproduce this issue.

```Lua
---
```

**Comment by mrcjkb** [comment]
Hey 👋 

Thanks for reporting!
I don't quite understand the steps to reproduce.
Could you please rephrase it in terms of commands?
E.g. 

```
nvim src/main.rs
:<cmd-to-open-windows
:RustLsp codeAction
...
```

Screenshots or an asciinema recording/gif can also be helpful. 🙏

**Comment by aikixd** [comment]
Sorry for the delay.
I've made a record with minimal config.
https://asciinema.org/a/Dbo3pcm21Ipgc5Amet6nEE6ET?t=59

I'm opening the code action twice:
 - one time i'm opening and closing the secondary with 'q'
 - second time i'm selecting an item in the secondary

Both times the cursor jumps to the left window.
