### ISSUE TITLE
note: 3.16.0 dap autoload freezes neovim unless it is disabled

### ISSUE THREAD

**Issue by thlorenz** [mrcjkb/rustaceanvim#170]
This is not exactly a bug since there is an easy workaround, but I felt it could be important to let you know and maybe help others find that workaround. It took me quite a bit of head scratching to find the source of my issue, so I want to save others the time.

I'm using your plugin on a very large project and the 3.16.0 release caused neovim to freeze and I could either wait a long time (up to a minute) or hit Ctrl-C to shortcut it. This happened every time I opened a new Rust file.

Fortunately with help of your detailed release notes (quoted  below) I found a quick workaround which completely fixes the issue:

```lua
-- anywhere before loading the `mrcjkb/rustaceanvim` plugin
vim.g.rustaceanvim = {
  dap = {
    autoload_configurations = false,
  },
}
```

> [3.16.0] - 2024-01-15
> Added
> DAP: Better nvim-dap integration:
> Automatically try to load Rust debug configurations on LSP attach.
> This lets you use require('dap').continue() instead of :RustLsp debuggables,
> once the configurations have been loaded.
> Can be disabled by setting vim.g.rustaceanvim.dap.autoload_configurations = false.

**Comment by mrcjkb** [comment]
Thanks for reporting :smile:

I presume you're using Neovim 0.9? This shouldn't be a problem with neovim 0.10.

🤔 Maybe I should disable the setting by default for neovim < 0.10.

**Comment by mrcjkb** [comment]
https://github.com/mrcjkb/rustaceanvim/pull/171

**Comment by thlorenz** [comment]
Thanks for the response, I'm indeed on v0.9 as this seems to be the version which `brew` [considers stable](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/n/neovim.rb#L7)

```
❯ nvim --version
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891
```

Thanks for fixing this so others don't have to figure out that setting.
