### ISSUE TITLE
Pass args to debuggables / runnables

### ISSUE THREAD

**Issue by pgherveou** [mrcjkb/rustaceanvim#181]
### Feature description

Hey there thanks for the excellent plugin.
In rust-tool I had this little patch to pass custom args to runnable / debuggable via environment variable 

https://github.com/pgherveou/rust-tools.nvim/commit/45dd1703daf52be185a274e3691323eafb75bc5d

Would you accept a PR that does something similar here?

**Comment by mrcjkb** [comment]
Hey :wave: 

Thanks for the suggestion! 
hat sounds reasonable. Let me sleep over it - maybe we can come up with a more convenient solution.

How do you currently use it with your patch? I suppose you set an environment variable in your project directory (e.g. with direnv) before starting Neovim?

Here are some other ideas on how we could achieve this:

- rustaceanvim supports loading project-specific debug configurations from a `.vscode/launch.json`.
  See also:
  -  https://github.com/mrcjkb/rustaceanvim/discussions/163
  - The [README's Usage/Debugging](https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#usage) section
- Another option would be a setting in the `vim.g.rustaceanvim` config table (something like `dap.executableArgsOverride`?)
  that could be loaded on a per-project basis using [`:h exrc`](https://neovim.io/doc/user/options.html#'exrc').
  
The reason I'd prefer something like that over an environment variable is that it's more explicit.

**Comment by pgherveou** [comment]
Ususally, for me, it's just a one of argument that I don't really  want to save in a config file.
I use this  command  to set it for me from vim when I need it
```lua
vim.api.nvim_create_user_command('RustExecArgs', function(opts)
  local args = table.concat(opts.fargs, ' ')
  vim.fn.setenv('RUST_EXECUTABLE_ARGS', args)
end, {
  nargs = '*',
})
```

This could probably be adapted to call a setter on the plugin module instead if we want to make it more explicit.

**Comment by mrcjkb** [comment]
🤔 What if I modify the commands `:RustLsp runnables` and `:RustLsp debuggables` to take an optional list of executable args?
And then `:RustLsp [runnables|debugganles]` last` would run the last command with the same args.

**Comment by pgherveou** [comment]
Yes that would work, that would force me to run the test through the command line instead of using the hover action, but that's a good enough I think

**Comment by mrcjkb** [comment]
> Yes that would work, that would force me to run the test through the command line instead of using the hover action, but that's a good enough I think

Oh, you're passing args to the test runner?
Have you tried [neotest-rust](https://github.com/rouge8/neotest-rust)? I prefer it over the hover actions/debuggables, and it supports passing args, afaict.
The `args` option can be a function, which you could use to set them from an environment variable.

I've been thinking of either adding support for neotest-rust to this plugin, or adding support for this plugin to neotest-rust (depending on what makes more sense - which I haven't investigated yet).
