### ISSUE TITLE
[Feat] Support RustOpenExternalDocs

### ISSUE THREAD

**Issue by vihu** [mrcjkb/rustaceanvim#19]
### Feature description

Hello,

Thank you for taking ownership of a maintained rust-tools plugin. I notice that opening external docs is gated behind experimental features. It's quite handy to be able to open rust documentation (for std library and dependencies) via `RustOpenExternalDocs` function which rust-tools supported OOB. Any chance you could please stabilize and let us know how to do it?

For reference, here's what I have in my config (for rust-tools):

```lua
    keys = {
        { "<leader>rd", ":RustOpenExternalDocs<CR>", desc = "open rust documentation" },
    },
```

Something similar provided by rustaceanvim would be very useful. Thanks!

**Comment by mrcjkb** [comment]
Hey :wave: 

Opening extenal docs [is an experimental feature of rust-analyzer](https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/lsp-extensions.md#open-external-documentation).

This plugin still supports it, but the commands have changed.
To open extenal docs, you can change your keymap to:

```
keys = {
        { "<leader>rd", ":RustLsp externalDocs<CR>", desc = "open rust documentation" },
},
```

See `:h rustaceanvim` for a full list of commands (you man need to run `:helptags ALL` to generate the help tags first.
