### ISSUE TITLE
Config: Get `edition` from cargo project

### ISSUE THREAD

**Issue by mrcjkb** [mrcjkb/rustaceanvim#195]
### Feature description

Currently, `tools.rustc.edition` defaults to `'2021'`. It can probably be determined dynamically from the cargo project metadata.

**Comment by tvsfx** [comment]
FYI, `conform.nvim` already does this: https://github.com/stevearc/conform.nvim/blob/25d48271e3d4404ba017cb92a37d3a681c1ad149/lua/conform/util.lua#L198

**Comment by mrcjkb** [comment]
@tvsfx thanks for the reminder.
I've implemented it using the `cargo metadata` command.
