### ISSUE TITLE
Commands for filtered workspace symbol searches

### ISSUE THREAD

**Issue by mrcjkb** [mrcjkb/rustaceanvim#198]
### Feature description

https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/lsp-extensions.md#workspace-symbols-filtering

**Comment by xzbdmw** [comment]
Is it not possible in neovim? I tryed telescope's lsp_dynamic_workspace_symbols and only shows result of current buffer not stdlib/crates, which is different from vscode.

**Comment by mrcjkb** [comment]
> Is it not possible in neovim? I tryed telescope's lsp_dynamic_workspace_symbols and only shows result of current buffer not stdlib/crates, which is different from vscode.

I'm sure it would be possible on the client side, too.
This issue is about sending request parameters to the rust-analyzer, so it can return pre-filtered results.

**Comment by xzbdmw** [comment]
<img width="571" alt="截屏2024-02-01 19 26 21" src="https://github.com/mrcjkb/rustaceanvim/assets/97848247/33fbe88d-572b-4125-bca9-c3a3be27af1d">
I tryed the builtin lsp and there is no result too..
