### ISSUE TITLE
Persist cached runnables/testables/debuggables per project between sessions

### ISSUE THREAD

**Issue by mrcjkb** [mrcjkb/rustaceanvim#200]
### Feature description

Also: If a runnable is for a specific buffer, it might be better to map them by buffer/file name

**Comment by cacharle** [comment]
Would you happen to have a workaround for this by any chance? (like some configuration for rust-analyzer itself rather than this plugin)

**Comment by mrcjkb** [comment]
Unfortunately, no.

Actually, I don't know why I thought this would be a good idea when I opened this issue. 
If anything, something like that would be the responsibility of rust-analyzer.
