### ISSUE TITLE
Hover Action has markdown artifacts

### ISSUE THREAD

**Issue by nathanielc** [mrcjkb/rustaceanvim#207]
### Neovim version (nvim -v)

v0.10.0-dev-2264+gbe1d09c427

### Operating system/version

6.6.10-arch1-1

### Output of :checkhealth rustaceanvim

```console
==============================================================================
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 1.75.0 (82e1608 2023-12-21)
- OK Cargo: found cargo 1.75.0 (1d8b05cdd 2023-11-20)
- OK rustc: found rustc 1.75.0 (82e1608df 2023-12-21)
- OK debug adapter: found codelldb 

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- OK tree-sitter parser for Rust detected.
```

### How to reproduce the issue

```console
Open rust file and trigger a hover action. Enter the hover action window and move the cursor to an empty line before a code snippet.


This might be a treesitter bug an not a rutasceanvim bug. Using tree-sitter-git version 0.20.9.r28.gff89b539-1 But I figured best to start here and be redirected otherwise as I observe the bug in the hover action logic.
```

### Expected behaviour

The hover shows in a window without the ```rust  markdown annotation

### Actual behaviour

There are empty lines around all of the code snippets in the hover window. When you move the cursor to one of these lines it reveals the markdown ``` backticks. This makes the hover window larger than needed and harder to read as a result.

![image](https://github.com/mrcjkb/rustaceanvim/assets/3771906/11cff1dc-3663-45ef-9eef-4b6c7e1049bb)

### The minimal config used to reproduce this issue.

```Lua
local Plug = vim.fn['plug#']
vim.call('plug#begin')
Plug('mrcjkb/rustaceanvim')
Plug('nvim-treesitter/nvim-treesitter')
vim.call('plug#end')
```

**Comment by mrcjkb** [comment]
Hey 👋 

What you're observing is tree-sitter based [concealing](https://neovim.io/doc/user/syntax.html#conceal).

Afaik, it's normal behaviour for a concealed element to be revealed when you move the cursor over it.
As rustaceanvim doesn't do anything related to concealing or highlights, I would suggest checking the neovim issue trackers.
However, I believe this is intended behaviour...

**Comment by nathanielc** [comment]
@mrcjkb Thanks for the quick reply, will go ask on neovim.
