### ISSUE TITLE
Jump in dependency coming from Github

### ISSUE THREAD

**Issue by Miaxos** [mrcjkb/rustaceanvim#22]
### Neovim version (nvim -v)

v0.9.4

### Operating system/version

macOS 12.3

### Output of `:checkhealth ferris`

 ============================================================================== rustaceanvim: require("rustaceanvim.health").check()  Checking for Lua dependencies ~ - OK [nvim-lua/plenary.nvim](https://github.com/nvim-lua/plenary.nvim) installed. - OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.  Checking external dependencies ~ - OK rust-analyzer: found rust-analyzer 1.75.0-nightly (49691b1f 2023-10-16) - OK Cargo: found cargo 1.75.0-nightly (6fa6fdc76 2023-10-10) - OK lldb-vscode: found   Checking config ~ - OK vim.g.rustaceanvim is set - OK No errors found in config.  Checking for conflicting plugins ~ - OK No conflicting plugins detected.

### How to reproduce the issue

First, thank you for this fork!

So here is the issue, when I jump in the declaration of a dependency fetched from github it causes an error and will not trigger the syntax highlighting of the dependency and not run the lsp inside too.

```
E5113: Error while calling lua 
chunk: ...te/pack/packer/opt/rustaceanvim/lua/rustaceanvim/lsp.lua:110: attempt to index upvalue 'methods' (a nil v
alue)                                                       
```

With a dependency declared like that for instance:

```Cargo.toml
openraft = { git = "https://github.com/datafuselabs/openraft", rev = "4b78dd38b9f3b22d87695fb06446dcf0311629c2" }
```

Then going to the definition of a type or anything declared from this dependency with `vim.lsp.buf.definition` will throw.

### Expected behaviour

Do not throw while jumping to git dependency.

### Actual behaviour

![image](https://github.com/mrcjkb/rustaceanvim/assets/1060101/73cba7d6-9fd6-437b-84b2-c68919c3c6df)

### The minimal config used to reproduce this issue.

Open a rust project and go to the definition of something exported by a crates fetched from github.

**Comment by mrcjkb** [comment]
Thanks for reporting! :smile:
