### ISSUE TITLE
Escape to close code actions

### ISSUE THREAD

**Issue by henryso** [mrcjkb/rustaceanvim#251]
### Feature description

Escape or `q` currently closes the hover actions floating window, but only `q` closes the grouped code actions floating window.  Would it be possible to have Escape also close the code actions floating window?

**Comment by mrcjkb** [comment]
Sure, why not? :smile: 

https://github.com/mrcjkb/rustaceanvim/commit/b44e1db9056d74cc491aa4a3f625f8bdca0d6743
