### ISSUE TITLE
[Feature request/needs triage] auto-detect mason.nvim installations of rust-analyzer

### ISSUE THREAD

**Issue by Alan-Manning** [mrcjkb/rustaceanvim#258]
### Neovim version (nvim -v)

v0.9.4

### Operating system/version

OS Name	Microsoft Windows 11 Pro N Version	10.0.22631 Build 22631

### Output of :checkhealth rustaceanvim

```console
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 0.3.1860-standalone (5346002d0 2024-02-25)
- OK Cargo: found 
- OK rustc: found 
- OK lldb: found 

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- OK tree-sitter parser for Rust detected.
```

### How to reproduce the issue

```console
i have mason to install rust-analyser, nvim-cmp for completions with has default capabilities.

i just installed the plugin through lazy and have not been able to get it working. i am coming from rust-tools where this did work nicely.


```

### Expected behaviour

The lsp server should start correctly.

### Actual behaviour

the lsp server seems to start but then exits with code 1 and signal 0

### The minimal config used to reproduce this issue.

I have condenced this a bit in terms of keymaps i made:

```lua
return {
	"mrcjkb/rustaceanvim",
	version = "^4", -- Recommended
	ft = { "rust" },
	config = function()
		local mason_registry = require("mason-registry")

		local codelldb = mason_registry.get_package("codelldb")
		local extension_path = codelldb:get_install_path() .. "/extension/"
		local codelldb_path = extension_path .. "adapter/codelldb"
		local liblldb_path = extension_path .. "lldb/lib/liblldb.dylib"

		vim.g.rustaceanvim = {
			-- Plugin configuration
			tools = {},
			-- LSP configuration
			server = {
				capabilities = require("cmp_nvim_lsp").default_capabilities(),
				on_attach = function(_, bufnr)
					-- you can also put keymaps in here

					local opts = { buffer = bufnr, silent = true }

					-- Code Actions
					opts.desc = "See available code actions"
					vim.keymap.set("n", "<leader>ca", function()
						vim.cmd.RustLsp("codeAction")
					end, opts)

					-- Show Documentation for what is under cursor
					opts.desc = "Show documentation under cursor"
					vim.keymap.set("n", "<leader>k", function()
						vim.cmd.RustLsp({ "hover", "actions" })
					end, opts)

					-- Explain Error
					opts.desc = "Explain Error"
					vim.keymap.set("n", "<leader>ex", function()
						vim.cmd.RustLsp("explainError")
					end, opts)

					-- Render Diagnostic
					opts.desc = "Render diagnostics"
					vim.keymap.set("n", "<leader>d", function()
						vim.cmd.RustLsp("renderDiagnostic")
					end, opts)

					-- SECTION BELOW IS COPIED FROM lspconfig.lua

					-- show definition, references
					opts.desc = "Show LSP references"
					vim.keymap.set("n", "gR", "<cmd>Telescope lsp_references<CR>", opts)
					--
					-- etc
					--
					-- mapping to restart lsp if necessary
					opts.desc = "Restart LSP"
					vim.keymap.set("n", "<leader>rs", ":LspRestart<CR>", opts)
				end,
				default_settings = {
					-- rust-analyzer language server configuration
					["rust-analyzer"] = {},
				},
			},
			-- DAP configuration
			dap = {},
		}
	end,
}

```

I am using nvim-lspconfig for everything else lsp. usually i would have:
```Lua
-- used to enable autocompletion (assign to every lsp server config)
local capabilities = cmp_nvim_lsp.default_capabilities()
--
--
lspconfig["rust_analyzer"].setup({
  capabilities = capabilities,
  on_attach = on_attach,
})
```
that will take the capabilities for nvim cmp and the on attach is just keymaps.

I am no longer calling that setup part of the code however as this plugin should call the setup if i read correctly. However when i dont call this i get the error above. from lsplog i see:
```console
[ERROR][2024-02-26 18:33:11] .../vim/lsp/rpc.lua:734	"rpc"	"rust-analyzer"	"stderr"	"error: 'rust-analyzer.exe' is not installed for the toolchain 'stable-x86_64-pc-windows-msvc'\n"
```
which makes me think that this plugin isnt seeing the mason install of rust-analyser?

When i do have that setup function being called in the lspconfig it is horrifically slow and does not really work at all, but the lsp does attach. i dont know what i need to do in order to make the plugin look at the lsp's i have installed vai mason but i think that is what i need?

Also i cant open ( or find at all ) the help doc from within nvim. dont know what thats about but very annoying.

**Comment by mrcjkb** [comment]
Hey :wave: 

Currently, this plugin does not pick up any mason.nvim installations of rust-analyzer.
Neither did rust-tools.nvim. The reason it used to work for you is that mason-lspconfig assumes you depend on nvim-lspconfig to initialize the LSP client (which was the case for rust-tools, but isn't for rustaceanvim), and configures nvim-lspconfig to use the mason installation.

The error message you're seeing is because this plugin is picking up a rustup wrapper for rust-analyzer, which delegates to the actual binary (see the [rust-analyzer installation manual](https://rust-analyzer.github.io/manual.html#installation)).
But the actual binary isn't installed.

I haven't paid much attention to automatically picking up rust-analyzer installations from mason.nvim, because it's usually recommended to use rustup. Afaik, with a mason installation, you might not get the right toolchain, and you'll have to rebuild your project when running `cargo build`, etc.

If you do want to use your mason installation, you can do so via the `vim.g.rustaceanvim.server.cmd` option, which can either be a list of strings or a function that returns a list of strings (see `:h rustaceanvim.config` and `:h RustaceanLspClientOpts`).

You could do something like this:

```lua
vim.g.rustaceanvim = {
  server = {
    cmd = function()
      local mason_registry = require('mason-registry')
      local package = mason_registry.get_package('rust-analyzer')
      local install_dir = package:get_install_path()
      -- find out where the binary is in the install dir, and append it to the install dir
      local ra_bin = install_dir .. '/' .. 'rust-analyzer.exe' -- this may need tweaking
      return { ra_bin } -- you can add additional args like `'--logfile', '/path/to/logfile'` to the list
    end,
  },
}
```

I don't use mason.nvim myself (as I mentioned I wouldn't recommend it for rust-analyzer).
So I won't be implementing auto-detection for mason.nvim rust-analyzer installs anytime soon.
But PRs are welcome. :smile:

I'll convert this issue to a feature request and leave it open in case someone wants to implement it.

**Comment by Pranav-Badrinathan** [comment]
> You could do something like this:
> 
> ```lua
> vim.g.rustaceanvim = {
>   server = {
>     cmd = function()
>       local mason_registry = require('mason-registry')
>       local package = mason_registry.get_package('rust-analyzer')
>       local install_dir = package:get_install_path()
>       -- find out where the binary is in the install dir, and append it to the install dir
>       local ra_bin = install_dir .. '/' .. 'rust-analyzer.exe' -- this may need tweaking
>       return { ra_bin } -- you can add additional args like `'--logfile', '/path/to/logfile'` to the list
>     end,
>   },
> }
> ```

Could the mason vimdoc be updated to include this as an example? Or somewhere else? I spent quite some time trying to figure out what the "cmd" was asking for. For an executable, it might be better to use `[lsp-server-name].[cmd/sh based on OS]` file that mason itself uses to launch the servers.

If you want I can test and then open a pull request with the correct format?

**Comment by Pranav-Badrinathan** [comment]
Alright! I understand completely the reasons for not including mason's RA by default, and why autodetection is probably not the best idea. I am of the opinion that users should configure rustaceanvim themselves if they want to use it. I was just advocating providing some sort of documentation for the same, like in `:h rustaceanvim.mason`. That was the PR I proposed, adding your example there to allow the people who want to configure their RA with mason to do so.

> But I'm happy to add a wiki page (which I'll do later today).
Thank you very much 😄.

**Comment by mrcjkb** [comment]
I've updated `:h rustaceanvim.mason` to include an example.

**Comment by cstrahan** [comment]
> I haven't paid much attention to automatically picking up rust-analyzer installations from mason.nvim, because it's usually recommended to use rustup.

Per this comment (emphasis mine): https://github.com/rust-lang/rust-analyzer/issues/14882#issuecomment-1561901169

> It's already documented in the manual. **But I suggest avoiding it, since you'll get a version that's months old and doesn't get any bug fixes.**
> 
> In addition, most people will probably use the Code extension, which comes with a compatible server.

I don't think using rustup's rust-analyzer is ideal, given that you'll be stuck with an old version (whatever was stable at the time of the respective toolchain was released).

The VSCode extension apparently doe _not_ depend on rustup, but rather manages its own installation of `rust-analyzer`.

**Comment by mrcjkb** [comment]
As I mentioned in a previous comment in this issue:

> with a mason installation, you might not get the right toolchain, and you'll have to rebuild your project when running cargo build, etc.

I more frequently see neovim users having issues with a mason.nvim rust-analyzer package, and they can typically solve them by using rustup instead. Personally, I use Nix devShells, which works great.

> The VSCode extension apparently doe not depend on rustup, but rather manages its own installation of rust-analyzer.

package management is out of scope for rustaceanvim.

Locking this issue as off topic.
