### ISSUE TITLE
Feature request: support removal of unused imports

### ISSUE THREAD

**Issue by mawkler** [mrcjkb/rustaceanvim#259]
### Feature description

Hi! It looks like [rust-analyzer has support for removing unused imports](https://github.com/rust-lang/rust-analyzer/pull/14723). Would this be possible to add to rustaceanvim?

**Comment by mrcjkb** [comment]
Hey :wave: 

afaict, this feature is implemented as a code action (`:RustLsp codeAction` or `vim.lsp.buf.code_action()`), which is already supported:

![remove-imports](https://github.com/mrcjkb/rustaceanvim/assets/12857160/e5da67ee-9739-43f1-a114-420c89c18fa0)

Or am I missing something?

**Comment by mawkler** [comment]
@mrcjkb "Remove all the unused imports" seems to do the same thing as "remove the unused import"/"remove the whole `use` item" i.e. remove only the _current line's_ unused imports. I have a feeling that "Remove all the unused imports" is supposed to remove the unused imports on _every_ `use` line. Do you know if this is the case?

**Comment by mrcjkb** [comment]
> @mrcjkb "Remove all the unused imports" seems to do the same thing as "remove the unused import"/"remove the whole `use` item" i.e. remove only the _current line's_ unused imports. I have a feeling that "Remove all the unused imports" is supposed to remove the unused imports on _every_ `use` line. Do you know if this is the case?

Yes, "Remove all the unused imports" removes unused imports on every `use` line.

**Comment by mrcjkb** [comment]
Removing unused imports on all `use` lines/organising imports is currently unsupported by rust-analyzer, but has been requested: https://github.com/rust-lang/rust-analyzer/issues/5131.

**Comment by mawkler** [comment]
I see, thanks!

**Comment by xzbdmw** [comment]
Put here something works automatically after you save... have to look at how `vim.lsp.buf.code_action` does
```lua
vim.api.nvim_create_autocmd("BufWritePost", {
    pattern = "*.rs",
    callback = function()
        local params = vim.lsp.util.make_range_params()
        params.context = {
            diagnostics = vim.tbl_map(function(d)
                return d.user_data.lsp
            end, vim.diagnostic.get(0)),
            triggerKind = 1,
        }
        params.range = {
            start = { line = 0, character = 0 },
            ["end"] = { line = #vim.api.nvim_buf_get_lines(0, 0, -1, false), character = 0 },
        }
        vim.lsp.buf_request(0, "textDocument/codeAction", params, function(err, result, context, config)
            for _, action in ipairs(result or {}) do
                if action.title == "Remove all the unused imports" then
                    local client = vim.lsp.get_client_by_id(context.client_id)
                    client.request("codeAction/resolve", action, function(err_resolve, resolved_action)
                        if err_resolve then
                            vim.notify(err_resolve.code .. ": " .. err_resolve.message, vim.log.levels.ERROR)
                            return
                        end
                        if resolved_action.edit then
                            vim.lsp.util.apply_workspace_edit(resolved_action.edit, client.offset_encoding)
                        end
                    end)
                    return
                end
            end
        end)
    end,
})
```
