### ISSUE TITLE
Debug exception

### ISSUE THREAD

**Issue by soulfresh** [mrcjkb/rustaceanvim#26]
### Neovim version (nvim -v)

v0.9.1 & v0.9.4

### Operating system/version

osx

### Output of `:checkhealth ferris`

OK

### How to reproduce the issue

Howdy,
I'm having a trouble getting debugging to work (both with lldb and codelldb). For me, `rustaceanvim/dap.lua` throws an error that `vim.list_contains` is nil.

I start a debug session with `RustLsp debuggables`, which thows:

```
Error executing vim.schedule lua callback: ...al/share/nvim/lazy/rustaceanvim/lua/rustaceanvim/dap.lua:46: attempt to call field 'list_contains' (a nil value)
```

I'm on the latest neovim. I'm not familiar with `vim.list_contains`. Could that be a deprecated method that was removed? Or is that a function added by some other plugin?

I tried following you reproduction steps for a minimal config but that config did not include debug functionality. Do you know which plugins I need to add to the minimal case to get a minimal config with the `RustLsp` command? 

### Expected behaviour

It should start a debug session

### Actual behaviour

Exception shown in messages window and debug session is never opened.

### The minimal config used to reproduce this issue.

```lua
  {
    'mrcjkb/rustaceanvim',
    version = '^3',
    ft = { 'rust' },
  },

```

**Comment by mrcjkb** [comment]
Hey 👋
Thanks for reporting!
That looks like the neovim nightly API may have slipped in due to a lack of linting with neovim 0.9 😅

I'll look into fixing that today.

**Comment by soulfresh** [comment]
Thanks for the quick reply! I'll give this a go tomorrow
