### ISSUE TITLE
Support switching features dynamically

### ISSUE THREAD

**Issue by Rjected** [mrcjkb/rustaceanvim#265]
### Feature description

I work on a project with multiple feature flags, and often large code blocks that are gated by these features. I don't configure these features at startup, and some of them are mutually exclusive. Is it possible to have a vim command switch the current features without editing my rust-analyzer config?

**Comment by mrcjkb** [comment]
Hey :wave: 

rust-analyzer doesn't support hot-swapping features at runtime.
You would have to restart the LSP client.

This plugin provides a `:RustAnalyzer restart` command, and
the configuration option, `vim.g.rustaceanvim.server.settings`, can be a function (see [Readme#How to dynamically load different rust-analyzer settings per project](https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#how-to-dynamically-load-different-rust-analyzer-settings-per-project).

You can use these to create keymaps and commands to change the configuration and restart rust-analyzer.

However, such a feature would be too much of an edge case, with too much added complexity, to be implemented in rustaceanvim.

**Comment by Rjected** [comment]
> Hey 👋
> 
> rust-analyzer doesn't support hot-swapping features at runtime. You would have to restart the LSP client.
> 
> This plugin provides a `:RustAnalyzer restart` command. And the configuration option, `vim.g.rustaceanvim.server.settings`, can be a function (see [Readme#How to dynamically load different rust-analyzer settings per project](https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#how-to-dynamically-load-different-rust-analyzer-settings-per-project)).
> 
> You can use these to create keymaps and commands to change the configuration and restart rust-analyzer.
> 
> However, such a feature would be too much of an edge case, with too much added complexity, to be implemented in rustaceanvim.

That makes sense, I'll try to use the `settings` and `:RustAnalyzer restart` to do what I need. Thanks!
