### ISSUE TITLE
Don't auto_attach for buffer without an actual file?

### ISSUE THREAD

**Issue by tomtomjhj** [mrcjkb/rustaceanvim#268]
### Feature description

When I `:setf rust` in a new buffer without name (e.g., created by `:new`), rust-analyzer panics with error msg like this:
```
thread 'LspServer' panicked at crates/paths/src/lib.rs:79:36:
expected absolute path, got 
``` 
The reason is that rust-analyzer expects usual file path, but rustaceanvim unconditionally attempts to attach any rust buffer even if its name is not an actual file path. This also happens for other kind of buffers with rust filetype, such as vim-fugitive's blob buffer, which has a name of form `fugitive:///path/to/file.rs`. 

To avoid this, I ended up adding something like this in my config:
```lua
    auto_attach = function()
      -- Only attach to buf with actual file. rust-analyzer expects real path and panics otherwise.
      local b = vim.api.nvim_get_current_buf()
      local path = vim.fs.normalize(vim.api.nvim_buf_get_name(b), { expand_env = false })
      return vim.bo[b].buftype == '' and path:sub(1,1) == '/'
    end,
```

While this worked for me, I believe this should be handled in rustaceanvim itself.

**Comment by mrcjkb** [comment]
Hey again :smile:

Thanks for the suggestion. It sounds reasonable off the top of my head.
I will have to make sure this also works for Windows, which can have paths that start with drive letters.
