### ISSUE TITLE
Smart last debug/run/test ables?

### ISSUE THREAD

**Issue by wakuflair** [mrcjkb/rustaceanvim#276]
### Feature description

Hi first thank you for this awesome plugin.

I am wondering can we get a "smart last command"?

For example `vim.cmd.RustLsp { 'debuggables', bang = true }` will fail if there is no last debug command,

so in this case, can we just ignore the `bang` argument?

**Comment by mrcjkb** [comment]
Sounds totally reasonable 😃

**Comment by xYx-c** [comment]
The workspace contains multiple executable programs,
Only one can be run in debug mode.
The same is true in normal running mode. Only one program can be run and the process will be automatically killed repeatedly.
The output log when running in normal mode is at the top. Can't it be displayed at the bottom like debug?

From Google Translate

**Comment by mrcjkb** [comment]
> The workspace contains multiple executable programs, Only one can be run in debug mode. The same is true in normal running mode. Only one program can be run and the process will be automatically killed repeatedly.

The detection of programs that can be debugged is handled by [rust-analyzer](https://rust-analyzer.github.io/), not rustaceanvim.

> The output log when running in normal mode is at the top. Can't it be displayed at the bottom like debug?

I'm not sure I understand this question. rustaceanvim provides some config options that you can use to influence what to use as a backend for running executors. See `:h rustaceanvim.config` and `:h RustaceanExecutor`.

> The main.rs file must be opened to start debugging or normal running. Can all projects in the workspace be automatically detected?

No. This is done by rust-analyzer, not rustaceanvim.
