### ISSUE TITLE
render diagnostic hides square brackets

### ISSUE THREAD

**Issue by Amleto** [mrcjkb/rustaceanvim#280]
### Neovim version (nvim -v)

v0.10.0-dev-2051+gee3d4f6b9

### Operating system/version

win11 + wsl

### Output of :checkhealth rustaceanvim

```console
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- WARNING dap not installed. Needed for debugging features [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap)

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 1.73.0-nightly (eb088b8 2023-08-05)
- OK Cargo: found cargo 1.73.0-nightly (d78bbf4bd 2023-08-03)
- OK rustc: found rustc 1.73.0-nightly (eb088b8b9 2023-08-05)

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- OK tree-sitter parser for Rust detected.
```

### How to reproduce the issue

make a compiler error that contains square brackets, e.g. something involving an array.

Sorry, I will update later - same for the config.

This bug looks similar to #200, in that treesitter is probably hiding the brackets, but I suspect this to be a rustacean issue if the filetype should not actually be set to markdown?

### Expected behaviour

render diagnostic looks like the compiler output

### Actual behaviour

The square brackets are gone (hidden). They reappear when focusing into the window setting the cursor on the same line as a 'bad render'.

### The minimal config used to reproduce this issue.

```Lua
.
again, apologies - will endeavour to update tomorrow
```

**Comment by mrcjkb** [comment]
Hey :wave: 

thanks for reporting!
A fix is in the pipeline :smile:

**Comment by Amleto** [comment]
Oh sweet! Thanks for looking into it even with the poor report 🙏🏻

I really like the render diag feature!

**Comment by Amleto** [comment]
@mrcjkb btw, I know how to 'enter' the hover window with 2x hover. The same thing doesn't work with render diagnostic - how does one enter the render diagnostic float? (or scroll it when its not active)?

**Comment by mrcjkb** [comment]
> @mrcjkb btw, I know how to 'enter' the hover window with 2x hover. The same thing doesn't work with render diagnostic - how does one enter the render diagnostic float? (or scroll it when its not active)?

I usually use `<C-w>` followed by `w` (cycle windows).
