### ISSUE TITLE
DAP: Support loading launch.json configurations

### ISSUE THREAD

**Issue by mrcjkb** [mrcjkb/rustaceanvim#29]
### Feature description

... as is done in haskell-tools.nvim.

**Comment by richchurcher** [comment]
Aha! I was about to add an issue, but I see you've anticipated it. Would it be OK if I picked this one up, as I have a current need for it? The use case is being able to override the `env` ([to allow for dynamic linking](https://github.com/vadimcn/codelldb/issues/632#issuecomment-1726665345) but obviously it'll be useful for lots of other things.

**Comment by richchurcher** [comment]
Whew. `env` is tricky cross-platform (dynamic libs use three different environment variables for three different platforms, and Windows insists on `;` separators). NVM, we can leave that detail to the user and just load whatever's in `launch.json`. I have a semi-working port, I'll try to tidy it up a bit. Unfortunately I don't have the capacity to test on nix right now, but I can do the basics.

**Comment by mrcjkb** [comment]
Hey :wave:

Contributions are more than welcome! Thanks so much, looking forward to it! :smile:

**Comment by richchurcher** [comment]
Well, TIL. `nvim-dap` has a whole `launch.json`-related help topic (`:h dap-launch.json`)! I did not realise that support had been added. Note also https://github.com/simrat39/rust-tools.nvim/wiki/Use-with-dap.ext.vscode-launch.json. So I will stop trying to reinvent the wheel and instead start figuring out how to accommodate their method.
