### ISSUE TITLE
config validation fails on valid nvim-dap config

### ISSUE THREAD

**Issue by xusd320** [mrcjkb/rustaceanvim#294]
### Neovim version (nvim -v)

v0.9.5 with LazyVim latest

### Operating system/version

macOS 13.6.4

### Output of :checkhealth rustaceanvim

```console
==============================================================================
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 0.3.1877-standalone (574e23ec5 2024-03-09)
- OK Cargo: found cargo 1.75.0-nightly (d2f6a0485 2023-10-20)
- OK rustc: found rustc 1.75.0-nightly (cd674d617 2023-10-24)
- OK debug adapter: found codelldb 

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- OK tree-sitter parser for Rust detected.
```

### How to reproduce the issue

```console
The problem is really wield, some steps to produce.
 1. In terminal, cd to a certain rust project directory.
 2. Open vim, then open telescope recent files picker, chose a file which not in the chosed directory at the first step, 
    and then open the file.
 4. Rustacean plugin ant treesitter plugin will not attach to the opened file buf, 
    that is rust-analyzer will not be launched automatically, and treesitter highlight not work.

Sorry for I can't provide a minimal config, because the problem happened only when at the first step, 
I cd to my company private project. And after step 3, if I open another rust files from the file tree, 
the rustacean will launch rust-analyzer and treesitter highlight will both work normally.

When use the old rust-tools before, there is no problem like this. After some debugging, I found that this is 
related to mason codelldb adapter. If I uninstall the codelldb adapter, rustacean will launch rust-analyzer 
and treesitter highlight will be ok too. 

I checked the rustaceanvim codes, found the auto_attach config, if setup it to be true, rustacean will always 
launch rust-analyzer normally, but the treesitter is still bad.

I don't want wasting other people's time， just need some help about how to debug this problem, thanks.
```

### Expected behaviour

 When open a rust file rust othen repo, rustacean will always launch rust-analyzer，and treessitter highlight will be ok

### Actual behaviour

 rustacean will not launch rust-analyzer, treesitter highlight will not work.

## Bad when start from this directory . 
At the and,  if I run ":e" in vim, it will be ok again.
![iShot_2024-03-16_19 33 12](https://github.com/mrcjkb/rustaceanvim/assets/16577489/a38accf5-75c8-41ad-acb5-72b34340b1e7)

When setup rustacean with auto_attach: true, rust-analyzer works ok, but tree sitter highlight not good.
![iShot_2024-03-16_19 40 46](https://github.com/mrcjkb/rustaceanvim/assets/16577489/236772d3-1311-4564-803c-4a42d3ea6477)

Afer uninstall codelldb adapter, every thing will be ok.
![iShot_2024-03-16_19 43 44](https://github.com/mrcjkb/rustaceanvim/assets/16577489/806a315e-c1a8-43cc-b650-b366568f8736)

## Good when start from another directory .
![iShot_2024-03-16_19 38 10](https://github.com/mrcjkb/rustaceanvim/assets/16577489/b20759d3-8ae8-4437-a4e5-c7a119eba2dc)

### The minimal config used to reproduce this issue.

```Lua
rust-analyzer ant treesitter highlight will be ok.
```

**Comment by mrcjkb** [comment]
Hey 👋 

Thanks for reporting.
Based on what you describe, it looks like an error is getting thrown were rustaceanvim looks for the mason codelldb installation, somewhere here:

https://github.com/mrcjkb/rustaceanvim/blob/69a22c2ec63ab375190006751562b62ebb318250/lua/rustaceanvim/config/internal.lua#L288

I am away from my laptop, but might have time to look into it tomorrow.
In the meantime, could you please try to reproduce this using plain Neovim (not LazyVim) and the minimal config I provide with this repo (see the readme's troubleshooting section). You can add mason.nvim to the minimal config, since it seems to be related.

LazyVim comes bundled with a lot of plugins, which makes it difficult for me to reproduce issues.
Also, a minimal config helps rule out or identify another plugin causing the issue.

**Comment by xusd320** [comment]
> Hey 👋
> 
> Thanks for reporting. Based on what you describe, it looks like an error is getting thrown were rustaceanvim looks for the mason codelldb installation, somewhere here:
> 
> https://github.com/mrcjkb/rustaceanvim/blob/69a22c2ec63ab375190006751562b62ebb318250/lua/rustaceanvim/config/internal.lua#L288
> 
> I am away from my laptop, but might have time to look into it tomorrow. In the meantime, could you please try to reproduce this using plain Neovim (not LazyVim) and the minimal config I provide with this repo (see the readme's troubleshooting section). You can add mason.nvim to the minimal config, since it seems to be related.
> 
> LazyVim comes bundled with a lot of plugins, which makes it difficult for me to reproduce issues. Also, a minimal config helps rule out or identify another plugin causing the issue.

Thanks. I found the problem is that 
https://github.com/mrcjkb/rustaceanvim/blob/69a22c2ec63ab375190006751562b62ebb318250/lua/rustaceanvim/config/check.lua#L147

Actually, dap.configuration.program can also be a function type according to this. Just change the checked to { 'string', 'function' }, then everything works well.

I made a PR to fix.
