### ISSUE TITLE
Windows rust-analyzer not found in checkhealth report but it is installed and working in VSCode

### ISSUE THREAD

**Issue by AddictArts** [mrcjkb/rustaceanvim#302]
### Have you read the docs and searched existing issues?

- [X] I have read [the README's troubleshooting guide](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#troubleshooting).
- [X] I have searched [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
- [X] I have searched [existing discussions](https://github.com/mrcjkb/rustaceanvim/discussions).
- [X] I have searched the existing issues of other plugins related to this issue.
- [X] I can reproduce the issue with stable Neovim (not a distribution or nightly) and the [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Windows 11

### Output of :checkhealth rustaceanvim

```console
- ERROR       rust-analyzer: not found.
```

### How to reproduce the issue

```console
Install neovim on Windows 11
Install the required plugins.
```

### Expected behaviour

It should be found, it is in the path and available. VSCode finds it.

### Actual behaviour

- ERROR       rust-analyzer: not found.

### The minimal config used to reproduce this issue.

```Lua
{
  'mrcjkb/rustaceanvim',
  version = '^4', -- Recommended
  ft = { 'rust' },
}
```

**Comment by AddictArts** [comment]
It says this - WARNING rust-analyzer wrapper detected. Run 'rustup component add rust-analyzer' to install rust-analyzer.
However that step has been performed.

**Comment by mrcjkb** [comment]
Hey 👋 

Thanks for reporting.
That's strange. This health check shouldn't be run in neovim 0.9.

Does the LSP client start as usual?

**Comment by mrcjkb** [comment]
https://github.com/mrcjkb/rustaceanvim/commit/b0548ff58d34caa220f8806c518fedb6453fc48e

**Comment by AddictArts** [comment]
@mrcjkb Yes it does seem the LSP client does start without any issue and :RustLsp logFile is empty, plus the status bar show LSP ~ rust-analyzer. Thanks for checking into this and the patch.
