### ISSUE TITLE
When applying code action escape character is inserted before }

### ISSUE THREAD

**Issue by AradiPatrik** [mrcjkb/rustaceanvim#303]
### Have you read the docs and searched existing issues?

- [X] I have read [the README's troubleshooting guide](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#troubleshooting).
- [X] I have searched [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
- [X] I have searched [existing discussions](https://github.com/mrcjkb/rustaceanvim/discussions).
- [X] I have searched the existing issues of other plugins related to this issue.
- [X] I can reproduce the issue with stable Neovim (not a distribution or nightly) and the [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

macOS 14.3.1 (23D60)

### Output of :checkhealth rustaceanvim

```console
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 0.0.0 (5346002d0 2024-02-25)
- OK Cargo: found cargo 1.76.0 (c84b36747 2024-01-18)
- OK rustc: found rustc 1.76.0 (07dca489a 2024-02-04)
- OK lldb: found lldb-1500.0.404.7

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- OK tree-sitter parser for Rust detected.
```

### How to reproduce the issue

```console
mkdir -p /tmp/minimal/
NVIM_DATA_MINIMAL="/tmp/minimal" NVIM_APP_NAME="nvim-minimal" nvim -u NORC -u minimal.lua
:edit main.rs
/impl<CR>
:lua vim.lua.buf.code_action()<CR>
1<CR>
```

### Expected behaviour

https://github.com/mrcjkb/rustaceanvim/assets/16306605/e00346dd-62c3-4d9d-848e-704e8c74060e

The expected behavior is to have regular closing braces generated `}`. 
Please check the video issue. It should be quite obvious.

### Actual behaviour

Right now closing braces are escaped for some reason `\}` instead of `}`
Please check the attached video.

### The minimal config used to reproduce this issue.

```Lua
The minimal config linked in the troubleshooting
```

**Comment by AradiPatrik** [comment]
The code to demonstrate the issue `main.rs`
``` rs
trait Messenger {
    fn send(&self, message: &str);
}

struct LimitTracker<'a, T: Messenger> {
    messenger: &'a T,
    value: u32,
    limit: u32,
}

impl<'a, T: Messenger> LimitTracker<'a, T> {
    fn set_value(&mut self, value: u32) {
        if self.limit as f32 / value as f32 > 0.5f32 {
            self.messenger.send("You've consumed half of your quota");
        } else if self.limit as f32 / value as f32 > 0.75f32 {
            self.messenger
                .send("Warning! You've consumed 75% of your quota");
        } else if self.limit as f32 / value as f32 > 0.9f32 {
            self.messenger
                .send("Urgent! You've consumed 90% of your quota");
        }

        self.value = value
    }
}

fn main() {}

```

**Comment by mrcjkb** [comment]
Hey :wave: 

Thanks for the detailed report. This is a rust-analyzer bug: https://github.com/rust-lang/rust-analyzer/issues/16607

**Comment by rami3l** [comment]
@mrcjkb Looks like the problem is more complicated than it seems...

Coming exactly from https://github.com/rust-lang/rust-analyzer/issues/16607, I made my own tests and saw that even on Neovim v0.10 I can still reproduce this issue with this plugin enabled. However, if I disable this plugin, then the completion works fine.

**Comment by mrcjkb** [comment]
> @mrcjkb Looks like the problem is more complicated than it seems...
> 
> Coming exactly from [rust-lang/rust-analyzer#16867](https://github.com/rust-lang/rust-analyzer/issues/16867), I made my own tests and saw that even on Neovim v0.10 I can still reproduce this issue with this plugin enabled. However, if I disable this plugin, then the completion works fine.

🤔 `vim.lua.buf.code_action()` isn't implemented by this plugin. It's a core neovim function.
So that sounds very fishy.

Are you sure you're using the same rust-analyzer version in both cases? Many neovim distributions use mason.nvim to install it.

**Comment by rami3l** [comment]
@mrcjkb Thanks a lot for your timely reply!

> Are you sure you're using the same rust-analyzer version in both cases?

I'm quite sure about this one. Initially I thought it was an r-a problem so that was my first thing to look into. However I do think the latest version of r-a is now generating the correct output.

> 🤔 `vim.lua.buf.code_action()` isn't implemented by this plugin. It's a core neovim function. So that sounds very fishy.

That's why I didn't think of disabling this plugin at first. However I'm not suggesting it's directly causing the problem.

I'm thinking in theory this plugin should do no harm to the whole code action thing, except it somehow puts RA into an output mode Neovim cannot handle properly.

After some more research I've found https://github.com/fannheyward/coc-rust-analyzer/commit/5059573c3e6bd8b31315f1abec6007da14f77fd4 to support this theory. Looks like it has something to do with:

https://github.com/mrcjkb/rustaceanvim/blob/597c8d6c7b4433ec4577b73bced1df41c132b077/lua/rustaceanvim/lsp.lua#L138

If this is the case, probably there're some problems remaining even with the updated Neovim after all.

**Comment by mrcjkb** [comment]
@rami3l wow thanks for the thorough research! 😀

If I have some time in the next days, I'll see if can find the issue in neovim.

In the meantime, you should be able to work around this by explicitly setting the capability to `false` via `vim.g.rustaceanvim.server.capabilities`.

**Comment by rami3l** [comment]
> @rami3l wow thanks for the thorough research! 😀
> 
> If I have some time in the next days, I'll see if can find the issue in neovim.
> 
> In the meantime, you should be able to work around this by explicitly setting the capability to `false` via `vim.g.rustaceanvim.server.capabilities`.

@mrcjkb Thanks for you pointers! Now I can 100% confirm that this problem can be worked around by setting `vim.g.rustaceanvim.server.capabilities.experimental.snippetTextEdit` to `false`.

**Comment by mrcjkb** [comment]
:thinking: I can't reproduce this with my personal config, but I can with a minimal one.
I wonder if there's a neovim setting or plugin that is fixing it in my config.

**Comment by elithrade** [comment]
> > @rami3l wow thanks for the thorough research! 😀
> > If I have some time in the next days, I'll see if can find the issue in neovim.
> > In the meantime, you should be able to work around this by explicitly setting the capability to `false` via `vim.g.rustaceanvim.server.capabilities`.
> 
> @mrcjkb Thanks for your pointers! Now I can 100% confirm that this problem can be worked around by setting `vim.g.rustaceanvim.server.capabilities.experimental.snippetTextEdit` to `false`.

@rami3l can I please ask how do you set `vim.g.rustaceanvim.server.capabilities.experimental.snippetTextEdit` to `false`? I am using LazyVim.

**Comment by mrcjkb** [comment]
> > > @rami3l wow thanks for the thorough research! 😀
> > > If I have some time in the next days, I'll see if can find the issue in neovim.
> > > In the meantime, you should be able to work around this by explicitly setting the capability to `false` via `vim.g.rustaceanvim.server.capabilities`.
> > 
> > 
> > @mrcjkb Thanks for your pointers! Now I can 100% confirm that this problem can be worked around by setting `vim.g.rustaceanvim.server.capabilities.experimental.snippetTextEdit` to `false`.
> 
> @rami3l can I please ask how do you set `vim.g.rustaceanvim.server.capabilities.experimental.snippetTextEdit` to `false`? I am using LazyVim.

See `:h rustaceanvim.config` and the [LazyVim documentation on the rust extension pack](https://www.lazyvim.org/extras/lang/rust).

**Comment by rami3l** [comment]
> 🤔 I can't reproduce this with my personal config, but I can with a minimal one. I wonder if there's a neovim setting or plugin that is fixing it in my config.

@mrcjkb Thanks again for your efforts! Would you like to share the minimal reproduction with Neovim? I guess it's still a problem to be addressed on their side...

**Comment by mrcjkb** [comment]
> > 🤔 I can't reproduce this with my personal config, but I can with a minimal one. I wonder if there's a neovim setting or plugin that is fixing it in my config.
> 
> @mrcjkb Thanks again for your efforts! Would you like to share the minimal reproduction with Neovim? I guess it's still a problem to be addressed on their side...

I am planning to look into it, but haven't had the time yet 😃
