### ISSUE TITLE
Neotest adapter marks all tests in module as failed if one of the tests inside module fails

### ISSUE THREAD

**Issue by AradiPatrik** [mrcjkb/rustaceanvim#321]
### Have you read the docs and searched existing issues?

- [X] I have read [the README's troubleshooting guide](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#troubleshooting).
- [X] I have searched [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
- [X] I have searched [existing discussions](https://github.com/mrcjkb/rustaceanvim/discussions).
- [X] I have searched the existing issues of other plugins related to this issue (if applicable).
- [X] I have searched the [existing rust-analyzer issues](https://github.com/rust-lang/rust-analyzer/issues?q=is%3Aissue+) (if applicable).
- [X] I can reproduce the issue with stable Neovim (not a distribution or nightly) and the [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

macOS 14.3.1 (23D60)

### Output of :checkhealth rustaceanvim

```console
==============================================================================
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 1.76.0 (07dca489 2024-02-04)
- OK Cargo: found cargo 1.76.0 (c84b36747 2024-01-18)
- OK rustc: found rustc 1.76.0 (07dca489a 2024-02-04)
- OK lldb: found lldb-1500.0.404.7

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- OK tree-sitter parser for Rust detected.
```

### How to reproduce the issue

```console
Install Neotest and the rustaceanvim adapter for it.

Create test module with multiple tests inside.

Run tests in the current file.

If both of them pass then both of them will have green checkmarks.
If one of them fail both of them will be marked with red cross --> This makes it harder to find the actual test that's failing.
```

### Expected behaviour

When one of the tests is failing inside a test module mark only that as failing and leave the green checkmark for the other passing tests in the neotest summary. In short: only mark tests as failing that are actually failing.

### Actual behaviour

If one test fails inside a test module all the tests inside that module will be marked as failing.

https://github.com/mrcjkb/rustaceanvim/assets/16306605/b795e342-95bb-4f56-8c4b-87967d0cdbb6

### The minimal config used to reproduce this issue.

```Lua
'nvim-neotest/neotest',
    dependencies = {
      'nvim-neotest/nvim-nio',
      'nvim-lua/plenary.nvim',
      'antoinemadec/FixCursorHold.nvim',
      'nvim-treesitter/nvim-treesitter',
    },
    opts = {
      adapters = { 'neotest-plenary' },
    },
    status = { virtual_text = true },
    output = { open_on_run = true },
```
require('neotest').setup {
  -- ...,
  adapters = {
    -- ...,
    require 'rustaceanvim.neotest',
  },
}
```

**Comment by mrcjkb** [comment]
Thanks for reporting.

As of now, the neotest adapter only parses test failures. If you run the whole test module, it'll mark the module position as failed, which neotest interprets as all tests failing.
It should be possible to determine the positions of passed tests from the output, and mark them as such. I will look into it soon.

**Comment by AradiPatrik** [comment]
Thanks!
