### ISSUE TITLE
Pass command line arguments to a runnable

### ISSUE THREAD

**Issue by andy941** [mrcjkb/rustaceanvim#323]
### Feature description

Is it possible to pass command-line arguments  to RustLsp runnables? I am compiling a Rust binary that takes CLI arguments and I can't find a way to use RustLsp runnables. The README says I can pass `[args[]]?` but it's not clear to me how. It would be great if in the list of `RustLsp runnables`  together with `run <target>` there was an option like `run <target> with arguments` and then that would prompt the user to enter CLI arguments. Then the binary can be run again with the same argument with `RustLsp runnables last`. What do you think?

Thank you for the great plugin,
Andrea

**Comment by mrcjkb** [comment]
Hey 👋 

Thanks for the suggestion 😄 

That could lead to a lot of choices to select from, and would likely overwhelm most users (passing arguments to runnables isn't too common, but modules with lots of test cases are).

With the `[args[]]?` option, you can just run `:RustLsp runnables arg1 arg2 arg3 ...` and it'll pass those args to whichever target you select.

**Comment by andy941** [comment]
Hi, I tried that  but with `RustLsp runnables arg1` I just get an error: `runnables: unexpected arguments: {"arg1"}`. If there is a way to put those in a launch.json file of sorts that would work too I think, not sure is the plugin currently supports something similar.

**Comment by mrcjkb** [comment]
> Hi, I tried that but with `RustLsp runnables arg1` I just get an error: `runnables: unexpected arguments: {"arg1"}`. If there is a way to put those in a launch.json file of sorts that would work too I think, not sure if the plugin currently supports something similar.

Then you're likely using an older version of this plugin. The feature was introduced with version 4.0.0.

You can use `.vscode/launch.json` with `:RustLsp debuggables` (see `:h dap-launch`).
