### ISSUE TITLE
Add support for opening docs.rs for symbol under cursor

### ISSUE THREAD

**Issue by liamwh** [mrcjkb/rustaceanvim#325]
### Feature description

Like so: https://www.reddit.com/r/rust/comments/w7cf7d/rustanalyzer_tip_open_docsrs_for_the_symbol_under/

I'm new to NeoVim, please forgive me if there is already an easy way to do this.

**Comment by mrcjkb** [comment]
The feature was already there, but I had forgotten to add the command :sweat_smile:
