### ISSUE TITLE
Instructions for setting rust-analyzer settings are wrong

### ISSUE THREAD

**Issue by eero-lehtinen** [mrcjkb/rustaceanvim#37]
Sorry but I don't want to fill a full bug report. 

But anyway the README instructions and and the default config show that you should set rust-analyzer settings like this:
```lua
vim.g.rustaceanvim = {
  server = {
    ['rust-analyzer'] = {}
  }
}
```

But that doesn't work.

The configuration needs to be
```lua
vim.g.rustaceanvim = {
  server = {
    settings = {
      ['rust-analyzer'] = {}
    }
  }
}
```
as shown [here](https://github.com/mrcjkb/rustaceanvim/blob/cee77f32fbbcea46ee054055703ce07fb42627cf/ci/schema/output.md).

The `server` key of the configuration is just passed to `vim.lsp.start` [here](https://github.com/mrcjkb/rustaceanvim/blob/cee77f32fbbcea46ee054055703ce07fb42627cf/lua/rustaceanvim/lsp.lua#L202C32-L202C32), and that requires lsp settings to be inside the `settings` key.

I took way too long fiddling with my rust-analyzer settings before noticing that they just weren't getting applied at all D:

**Comment by mrcjkb** [comment]
Hey :smile: 

Thanks again for the detailed report and the fix!
