### ISSUE TITLE
Is there a way I can use mini.notify to display diagnostics

### ISSUE THREAD

**Issue by alekspickle** [mrcjkb/rustaceanvim#376]
### Feature description

I want to setup rustaceanvim and display all the diagnostics to use mini.notify

**Comment by mrcjkb** [comment]
Hey :wave: 

This plugin uses Neovim's built-in LSP client to provide diagnostics.
For integrating with mini.notify, you're probably better off asking there.

**Comment by olekspickle** [comment]
If anyone else would like to make it work - [noice](https://github.com/folke/noice.nvim) does exactly what you'd want, whether you are mini cult member or an OG `notify.nvim` user
