### ISSUE TITLE
Plugin doesn't starts rust-analyzer on Windows

### ISSUE THREAD

**Issue by TheRustifyer** [mrcjkb/rustaceanvim#379]
### Have you read the docs and searched existing issues?

- [X] I have read [the README's troubleshooting guide](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#stethoscope-troubleshooting).
- [X] I have searched [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
- [X] I have searched [existing discussions](https://github.com/mrcjkb/rustaceanvim/discussions).
- [X] I have searched the existing issues of other plugins related to this issue (if applicable).
- [X] I have searched the [existing rust-analyzer issues](https://github.com/rust-lang/rust-analyzer/issues?q=is%3Aissue+) (if applicable).
- [ ] I can reproduce the issue with stable Neovim (not a distribution or nightly) and the [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).

### Neovim version (nvim -v)

v0.10.0-dev-3060+gd26943a6e

### Operating system/version

Windows 11

### Output of :checkhealth rustaceanvim

```console
.: require("..health").check()

- ERROR Failed to run healthcheck for "." plugin. Exception:
  [string "require("..health").check()"]:1: module '..health' not found:
  	no field package.preload['..health']
  cache_loader: module ..health not found
  cache_loader_lib: module ..health not found
  	no file '.\\\health.lua'
  	no file 'C:\Program Files (x86)\nvim\bin\lua\\\health.lua'
  	no file 'C:\Program Files (x86)\nvim\bin\lua\\\health\init.lua'
  	no file '.\\\health.dll'
  	no file 'C:\Program Files (x86)\nvim\bin\\\health.dll'
  	no file 'C:\Program Files (x86)\nvim\bin\loadall.dll'
  	no file '.\.dll'
  	no file 'C:\Program Files (x86)\nvim\bin\.dll'
  	no file 'C:\Program Files (x86)\nvim\bin\loadall.dll'
```

### How to reproduce the issue

```console
Install neovim on Windows 11
Install the required plugins
```

### Expected behaviour

It should be found, it is in the path and available. VSCode finds it.

### Actual behaviour

Plugin doesn't starts rust-analyzer

### The minimal config used to reproduce this issue.

```Lua
{
  'mrcjkb/rustaceanvim',
  version = '^4', -- Recommended
  ft = { 'rust' },
}
```

**Comment by mrcjkb** [comment]
Hey 👋 

Your `checkhealth` output tells be there's probably something wrong with your neovim installation.
