### ISSUE TITLE
neotest: remove `--show-output` flag when running with cargo-nextest

### ISSUE THREAD

**Issue by mrcjkb** [mrcjkb/rustaceanvim#383]
Hey 👋 

It looks like the executable you are using to run tests doesn't support the `--show-output` flag (which is provided by rust-analyzer).
rustaceanvim will use cargo-nextest if you have it installed.
You can try disabling that by setting `vim.g.rustaceanvim.tools.enable_nextest = false`.

If that fixes it, then it's probably a bug in rustaceanvim, and the command should probably be sanitised for cargo-nextest.

_Originally posted by @mrcjkb in https://github.com/mrcjkb/rustaceanvim/discussions/382#discussioncomment-9313001_

**Comment by nikensss** [comment]
Crazy how fast it was solved... thanks a lot! Just tested it and it does work on my machine! 🥳
