### ISSUE TITLE
commit `feat(dap): auto-generate source map to allow stepping into std` breaks non lldb debugging

### ISSUE THREAD

**Issue by igorlfs** [mrcjkb/rustaceanvim#40]
### Neovim version (nvim -v)

v0.10.0-dev-1386+g6c87d3e0fb

### Operating system/version

ArchLinux 6.5.9

### Output of `:checkhealth rustaceanvim`

rustaceanvim: require("rustaceanvim.health").check()  Checking for Lua dependencies ~ - OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.  Checking external dependencies ~ - OK rust-analyzer: found rust-analyzer 0.3.1713-standalone - OK Cargo: found cargo 1.73.0 - OK rustc: found rustc 1.73.0 (cc66ad468 2023-10-03) (Arch Linux rust 1:1.73.0-1) - OK lldb: found lldb version 16.0.6  Checking config ~ - OK vim.g.rustaceanvim is set - OK No errors found in config.  Checking for conflicting plugins ~ - OK No conflicting plugins detected.

### How to reproduce the issue

Set the debug adapter do codelldb, ie

```lua
dap = {
    adapter = {
         type = "server",
         port = "${port}",
         executable = {
            command = "codelldb",
            args = { "--port", "${port}" },
        },
    },
},
```

Try to launch a debug session

### Expected behaviour

Debugging with codelldb should work just fine.

### Actual behaviour

An error will be thrown, since codelldb doesn't support `{ sourceMap = source_map }` (I assume)

### The minimal config used to reproduce this issue.

Shouldn't go beyond the setting in the "how to reproduce" setting

**Comment by mrcjkb** [comment]
Hey 👋 

Thanks for the detailed report!
I'll see if I can find a fix later today.

For now, you should be able to work around it by setting

```lua
vim.g.rustaceanvim = {
  dap = {
    auto_generate_source_map = false,
  }
}
```

**Comment by mrcjkb** [comment]
🤔 according to https://github.com/vadimcn/codelldb/issues/184, `codelldb` should be able to handle `sourceMap` configurations. Maybe it's something else causing the error?

Anyways, I'll disable source map generation for `codelldb` by default for now and will look into it in more detail later.

**Comment by mrcjkb** [comment]
I think this may have to do with how the non-default config is merged with the default one.

**Comment by mrcjkb** [comment]
> Indeed, since auto_generate_source_map = false doesn't actually change anything.

I think I have a fix in mind :)

> is there any reason to use lldb over codelldb as the default adapter?

`codelldb` isn't packaged for as many distributions,. And on many distributions, you have to install it via the VSCode plugin and manually configure the paths. That makes it a lot harder to automate.

**Comment by igorlfs** [comment]
> I think I have a fix in mind :)

Thanks for the quick fix!

> `codelldb` isn't packaged for as many distributions

(if we were to switch to `codelldb`) I'd recommend using Mason to install it (you could have that as suggestion in the README), it handles the `PATH` and it's pretty much painless (though it'd be an additional dependency). Any thoughts?

**Comment by mrcjkb** [comment]
> I'd recommend using Mason to install it

I'm personally not a fan of the idea of using a Neovim plugin to manage packages, which is why I would recommend either Nix, Ansible, or the distro's package manager.

Version 3.4.0 will automatically set up a `dap` configuration for `codelldb` if it detects it on the `PATH`, but that's about as far as I'm willing to go regarding this plugin's responsibilities.

I do, however, plan on adding some more detailed documentation about DAP configuration: #42.

**Comment by igorlfs** [comment]
> Version 3.4.0 will automatically set up a dap configuration for codelldb if it detects it on the PATH, but that's about as far as I'm willing to go regarding this plugin's responsibilities.

Nice, thanks!

You're doing a wonderful job keeping this plugin alive!
