### ISSUE TITLE
Suspicious snippet in config/server.lua

### ISSUE THREAD

**Issue by tomasbarton-stemcell** [mrcjkb/rustaceanvim#406]
While trying to figure out why my rust analyzer does not show any diagnostic I noticed a strange snippet:

https://github.com/mrcjkb/rustaceanvim/blob/a73e8618d8518b2a7434e1c21e4da4e66f21f738/lua/rustaceanvim/config/server.lua#L57

imho this variable should be initialized to false

**Comment by mrcjkb** [comment]
That is indeed very suspicious :sweat_smile: 
Nice find!

**Comment by mrcjkb** [comment]
https://github.com/mrcjkb/rustaceanvim/commit/e306c742bd7f7183e371cd91268b72d9db1bbae0
