### ISSUE TITLE
Suggestion: start LSP client in BufEnter

### ISSUE THREAD

**Issue by lbiaggi** [mrcjkb/rustaceanvim#407]
### Feature description

Moving the LSP start to `BufEnter` event reduces ~ 20-30% of the startup, which is really helpful when opening in an RPI.

IMO, moving to `BufEnter`felt more smoothly

I achieve it through by disabling auto-attach and running the original command.

```lua
...
auto_attach = function(bufnr)
            local augroup = _G.custom.commands.augroup
            augroup("RUST_LSP", {
                {
                    event = "BufEnter",
                    pattern = "*.rs",
                    command = function()
                        require("rustaceanvim.lsp").start()
                    end,
                    once = true,
                },
            })

            return false
        end,
...
 ```

I wonder if this would be beneficial for other users / more powerful environment

**Comment by mrcjkb** [comment]
Sounds reasonable :smile: 

I've pushed the change to `master`, but I'll wait a bit before publishing a release, to see if someone complains.

**Comment by mrcjkb** [comment]
@lbiaggi I've [had to revert this](https://github.com/mrcjkb/rustaceanvim/commit/9d3ee35b62d84f0657ef2202ebde132df5bc6cf9) because it led to problems with the LSP client starting at all, and I don't know if it has any other side effects.

**Comment by lbiaggi** [comment]
> @lbiaggi I've [had to revert this](https://github.com/mrcjkb/rustaceanvim/commit/9d3ee35b62d84f0657ef2202ebde132df5bc6cf9) because it led to problems with the LSP client starting at all, and I don't know if it has any other side effects.

Yeek, seriously? Could you give me an example?

**Comment by mrcjkb** [comment]
> Yeek, seriously? Could you give me an example?

I don't have a repro myself.
https://github.com/mrcjkb/rustaceanvim/issues/408#issuecomment-2131653221

In any case, the uncertainty is enough reason to revert it. You seem to have a workaround that works for you, and this is an edge case.

**Comment by lbiaggi** [comment]
Yeah you are right about my use being an edge case. I'm just curious,
because I would like to help/debug it.

**Comment by mrcjkb** [comment]
The [official recommendation](https://neovim.io/doc/user/lsp.html#lsp-quickstart) is for `vim.lsp.start` to be called on a `FileType` event.
I fear that deferring to `BufEnter` **could have unexpected side effects**. So even if we were to fix this particular case, I won't include this in rustaceanvim.

**Comment by lbiaggi** [comment]
Look, I'm not gonna argue with you about this ("the official statement")
which is just an example.

But as I've said before it was just a suggestion if it doesn't work for the
others, I keep doing it on my own for my use case, as I have been doing
anyway. I was really curious about what caused it, it wasn't my intention
to try to force it into mainline, sorry for the confusion and noise.

Btw, you did a good work with the plugin
