### ISSUE TITLE
inlay_hint api change on 0.10

### ISSUE THREAD

**Issue by Madoshakalaka** [mrcjkb/rustaceanvim#408]
### Have you read the docs and searched existing issues?

- [X] I have read [the README's troubleshooting guide](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#stethoscope-troubleshooting).
- [X] I have searched [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
- [X] I have searched [existing discussions](https://github.com/mrcjkb/rustaceanvim/discussions).
- [ ] I have searched the existing issues of other plugins related to this issue (if applicable).
- [ ] I have searched the [existing rust-analyzer issues](https://github.com/rust-lang/rust-analyzer/issues?q=is%3Aissue+) (if applicable).
- [X] I can reproduce the issue with stable Neovim (not a distribution or nightly) and the [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

Ubuntu

### Output of :checkhealth rustaceanvim

```console
==============================================================================
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 1.77.0-nightly (bf3c6c5 2024-02-01)
- OK Cargo: found cargo 1.77.0-nightly (7bb7b5395 2024-01-20)
- OK rustc: found rustc 1.77.0-nightly (bf3c6c5be 2024-02-01)
- WARNING       debug adapter: not found.
        Install [lldb](https://lldb.llvm.org/) for extended capabilities.
              A debug adapter (defaults to: LLDB).
        Required for debugging features.
      
        

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.
```

### How to reproduce the issue

```console
open any rust project with neovim >= 0.10
```

### Expected behaviour

works

### Actual behaviour

this error

![image](https://github.com/mrcjkb/rustaceanvim/assets/44753941/f9171fd1-ff93-40c7-9a10-3b1970752d69)

### The minimal config used to reproduce this issue.

```Lua
no special config required
```

**Comment by Madoshakalaka** [comment]
https://github.com/neovim/neovim/commit/e3ec974324bd73b63f54503480a4e48d1887f8d9#diff-3b3a433b8799463f3cb0bcfbb0f1b699c0b949e7e31516e82b94a9c6aea3b395R374-R377

this is the culprit

Since 0.10.0 just dropped, this should be accommodated for

**Comment by mrcjkb** [comment]
This has been fixed already. Please update rustaceanvim.

**Comment by Madoshakalaka** [comment]
thanks! I have been using ` version = '^3'` in my config following the old readme...

**Comment by pacak** [comment]
I'm running 90bfbc5 with nvim 0.10.0 in form of appimage and getting this:

```
Error detected while processing LspAttach Autocommands for "*":
Error executing lua callback: ...6yVHDQ/usr/share/nvim/runtime/lua/vim/lsp/inlay_hint.lua:408: filter: expected table, got boolean
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        ...6yVHDQ/usr/share/nvim/runtime/lua/vim/lsp/inlay_hint.lua:408: in function 'enable'
        [string ":lua"]:4: in function <[string ":lua"]:3>
        [C]: in function 'nvim_exec_autocmds'
        ..._vim6yVHDQ/usr/share/nvim/runtime/lua/vim/lsp/client.lua:946: in function '_on_attach'
        ..._vim6yVHDQ/usr/share/nvim/runtime/lua/vim/lsp/client.lua:615: in function '
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

But to get that I have to type `:lua require'lspconfig'.rust_analyzer.setup{}`, otherwise it's not trying to start at all.


`rustaceanvim` seem to be able to see `rust-analyzer`

```
     rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies
- OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.

Checking external dependencies
- OK rust-analyzer: found rust-analyzer 1.78.0 (9b00956 2024-04-29)
- OK Cargo: found cargo 1.78.0 (54d8815d0 2024-03-26)
- OK rustc: found rustc 1.78.0 (9b00956e5 2024-04-29)

Checking config
- OK No errors found in config.

Checking for conflicting plugins
- OK No conflicting plugins detected.

Checking for tree-sitter parser
- OK tree-sitter parser for Rust detected.
```

All the plugins are at their most recent versions.

**Comment by mrcjkb** [comment]
>But to get that I have to type `:lua require'lspconfig'.rust_analyzer.setup{}`

rustaceanvim doesn't use lspconfig.

> otherwise it's not trying to start at all.

Interesting. Does it work if you use the latest tag (or a commit before https://github.com/mrcjkb/rustaceanvim/commit/90bfbc588fef7e44d82e5aba8dfc787e8d3f5d1a)?
I haven't created a release tag for that yet, because I feared it could cause unexpected problems.

**Comment by pacak** [comment]
> rustaceanvim doesn't use lspconfig.

Correct. It's not trying to start at all in this case.

> Interesting. Does it work if you use the latest tag (or a commit before https://github.com/mrcjkb/rustaceanvim/commit/90bfbc588fef7e44d82e5aba8dfc787e8d3f5d1a)?

And using previous commit fixes the starting issue. I'm getting the same error message though as before but I don't have to do anything to get it. Progress :)

**Comment by mrcjkb** [comment]
> And using previous commit fixes the starting issue. 

Alright, then I'll revert that commit.

> I'm getting the same error message though as before but I don't have to do anything to get it. Progress :)

If your neovim is up-to-date, and rustaceanvim is too, then it's probably coming from your own config or another plugin.

**Comment by mrcjkb** [comment]
> > And using previous commit fixes the starting issue.
> 
> Alright, then I'll revert that commit.
> 

Reverted.

**Comment by pacak** [comment]
> If your neovim is up-to-date, and rustaceanvim is too, then it's probably coming from your own config or another plugin.

Could be. I'll see if I can still reproduce it with all the plugins disabled.
