### ISSUE TITLE
Symbol search kind default not being applied correctly

### ISSUE THREAD

**Issue by willhansen** [mrcjkb/rustaceanvim#410]
### Have you read the docs and searched existing issues?

- [X] I have read [the README's troubleshooting guide](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#stethoscope-troubleshooting).
- [X] I am using the latest rustaceanvim release.
- [X] I have searched [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
- [X] I have searched [existing discussions](https://github.com/mrcjkb/rustaceanvim/discussions).
- [X] I have searched the existing issues of other plugins related to this issue (if applicable).
- [X] I have searched the [existing rust-analyzer issues](https://github.com/rust-lang/rust-analyzer/issues?q=is%3Aissue+) (if applicable).
- [X] I can reproduce the issue with stable Neovim (not a distribution or nightly) and the [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).

### Neovim version (nvim -v)

v0.10

### Operating system/version

Operating System: Linux Mint 21.3, Nixpkgs 23.11

### Output of :checkhealth rustaceanvim

```console
==============================================================================
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- WARNING dap not installed. Needed for debugging features [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap)

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 2024-04-08
- OK Cargo: found cargo 1.77.1
- OK rustc: found rustc 1.77.1 (7cf61ebde 2024-03-27) (built from a source tarball)
- OK lldb: found lldb version 17.0.6

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- OK tree-sitter parser for Rust detected.
```

### How to reproduce the issue

```console
:Telescope lsp_document_symbols
```

### Expected behaviour

see all symbols (like functions)

### Actual behaviour

see only types

Suspected cause:

https://github.com/rust-lang/rust-analyzer/blob/a55e8bf09cdfc25066b77823cc98976a51af8a8b/crates/rust-analyzer/src/config.rs#L2758
- `all_symbols`

https://github.com/mrcjkb/rustaceanvim/blob/90bfbc588fef7e44d82e5aba8dfc787e8d3f5d1a/lua/rustaceanvim/commands/workspace_symbol.lua#L14
- `allSymbols`

### The minimal config used to reproduce this issue.

Using lazy.nvim

Has issue:
```Lua
{
    "mrcjkb/rustaceanvim",
    version = '^4', -- Recommended
    lazy = false, -- load on startup
},
```

This seems to fix it:
```Lua
{
    "mrcjkb/rustaceanvim",
    version = '^4', -- Recommended
    lazy = false, -- load on startup
    opts = {
    },
    config = function(_, opts) 
      vim.g.rustaceanvim = {
        server = {
          default_settings = {
            ['rust-analyzer'] = {
              workspace = {
                symbol = {
                  search = {
                    kind = "all_symbols"
                  }
                }
              }
            }
          }
        }
      }
    end
  },
```

**Comment by mrcjkb** [comment]
Hey :wave: 

The "suspected cause" you listed [is correct](https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/lsp-extensions.md#workspace-symbols-filtering).
That request is made only by the `:RustLsp workspaceSymbol` command.

`:Telescope lsp_document_symbols` uses Neovim's built-in request, which, as you've correctly discovered, needs to be configured in the rust-analyzer settings.
