### ISSUE TITLE
Shortcut to open relevant Cargo.toml

### ISSUE THREAD

**Issue by bbaldino** [mrcjkb/rustaceanvim#437]
### Feature description

In my config I added a shortcut to open the relevant `Cargo.toml` based on the currently-opened file, any thoughts on adding support for this in rustaceanvim?  For reference what I had:

```lua
  local function open_cargo_file()
    local cargo_file = vim.fn.findfile("Cargo.toml", ".;")
    vim.cmd('vnew ' .. cargo_file)
  end
```

**Comment by mrcjkb** [comment]
Hey 👋 

There's already `:RustLsp openCargo`

**Comment by bbaldino** [comment]
Ah great, thanks!
