### ISSUE TITLE
RustLsp openDocs does not work properly on Macros

### ISSUE THREAD

**Issue by DJPoland** [mrcjkb/rustaceanvim#438]
### Have you read the docs and searched existing issues?

- [X] I have read [the README's troubleshooting guide](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#stethoscope-troubleshooting) and FAQ(https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#left_speech_bubble-faq).
- [X] I am using the latest rustaceanvim release.
- [X] I have searched [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
- [X] I have searched [existing discussions](https://github.com/mrcjkb/rustaceanvim/discussions).
- [X] I have searched the existing issues of other plugins related to this issue (if applicable).
- [X] I have searched the [existing rust-analyzer issues](https://github.com/rust-lang/rust-analyzer/issues?q=is%3Aissue+) (if applicable).
- [X] I can reproduce the issue with stable Neovim (not a distribution or nightly) and the [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

MacOS Sonoma 14.1

### Output of :checkhealth rustaceanvim

```console
n/a
```

### How to reproduce the issue

```console
When running RustLsp openDocs, it fails to redirect to the proper documentation page for certain symbols like macros. When running  openDocs over a ```vec!```, the following page: https://doc.rust-lang.org/stable/alloc/macros/macro.vec.html opens up which is nothing of significance.
```

### Expected behaviour

It should redirect to the page: [https://doc.rust-lang.org/std/macro.vec.html](https://doc.rust-lang.org/std/macro.vec.html) and not [https://doc.rust-lang.org/stable/alloc/macros/macro.vec.html](https://doc.rust-lang.org/stable/alloc/macros/macro.vec.html).

### Actual behaviour

Redirects to [https://doc.rust-lang.org/stable/alloc/macros/macro.vec.html](https://doc.rust-lang.org/stable/alloc/macros/macro.vec.html), which is not information about the macro.

### The minimal config used to reproduce this issue.

```Lua
n/a. Vanilla and latest commit of rustaceanvim.
```

**Comment by mrcjkb** [comment]
Hey 👋 

This is a rust-analyzer bug: https://github.com/rust-lang/rust-analyzer/issues/16724
