### ISSUE TITLE
Run clippy via command only (not on save)

### ISSUE THREAD

**Issue by jbuckmccready** [mrcjkb/rustaceanvim#453]
### Feature description

I'd like to be able to have only `cargo check` on save but still be able to run `clippy` via `flyCheck` manually (feeding results into lsp diagnostics).

I saw this: https://github.com/mrcjkb/rustaceanvim/discussions/334 but from what I can tell the way things are working it's all or nothing, with these being the only possibilities:
- enable `clippy` and run `clippy` on save
- disable `clippy` entirely (cannot run manually) with only `check` on save
- disable on save entirely and then run `check` or `clippy` manually via `flyCheck`

I want `check` on save, with `flyCheck` using clippy, e.g., `:RustLsp flyCheck run clippy`.

**Comment by mrcjkb** [comment]
Hey 👋 

Something like that can't be implemented by this plugin. 
You'll have to request it in the rust-analyzer issues.

**Comment by jbuckmccready** [comment]
https://github.com/mfussenegger/nvim-lint/issues/256 😬 

Thanks for response, awkward situation, was hoping to get the diagnostics fed into the lsp so I can use telescope to jump between them rather than running form command line and having to jump to file+line independent of telescope.

**Comment by mrcjkb** [comment]
It shouldn't be hard to contribute clippy support to nvim-lint:

- Use [an existing linter as a reference](https://github.com/mfussenegger/nvim-lint/blob/master/lua/lint/linters/hlint.lua).
- Set `cmd = "cargo"` and `args = { "clippy", "--message-format=json" }`.
- Adjust the parsing logic.

> was hoping to get the diagnostics fed into the lsp so I can use telescope to jump between them rather than running from command line and having to jump to file+line independent of telescope.

Both the LSP client and nvim-lint use the same`vim.diagnostic` API. So this shouldn't be an issue.
