### ISSUE TITLE
Config for placement of diagnostics float

### ISSUE THREAD

**Issue by GordianDziwis** [mrcjkb/rustaceanvim#455]
### Feature description

I have a function for lsp-diagnostics, whihc place the diagnostic float in the lower left corner:

```lua
            local _, winnr = vim.diagnostic.open_float({ source = true })
            if winnr then
                local width = vim.api.nvim_get_option("columns")
                local height = vim.api.nvim_get_option("lines")
                local config = {
                  anchor = 'SW',
                  relative = 'editor',
                  row = height - 2,
                  col = 1,
                }
                vim.api.nvim_win_set_config(winnr, config)
            end
```

Because rusteceanvim does not show hints and info diagnostic levels, I have a function to fall back to lsp diagnostics in `ftplugin/rust.lua:

```lua
local bufnr = vim.api.nvim_get_current_buf()
local opts = { silent = true, buffer = bufnr }
vim.keymap.set("n", "<localleader>e", function()
    local output = vim.fn.execute('RustLsp renderDiagnostic current')
    if output:match("No renderable diagnostics found.") then
        vim.cmd('lua _G.show_diagnostics()')
    end
end, opts)
```

But now the diagnostic float placement is inconsistent between native diagnostics and rustaceanvim.

Can I modify the window placement for `RustLsp renderDiagnostic current` dynamically?

**Comment by mrcjkb** [comment]
Hey 👋 

You can configure rustaceanvim's floating windows with `vim.g.rustaceanvim.tools.float_win_config`.

See `:h rustaceanvim.config`.

If that doesn't provide what you're looking for, PRs are welcome 😀.

**Comment by GordianDziwis** [comment]
@mrcjkb Is this config lazily evaluated on creation of a float?

**Comment by mrcjkb** [comment]
> @mrcjkb Is this config lazily evaluated on creation of a float?

No.

**Comment by retarpt** [comment]
Is there a way to modify the width/height of the floating windows? When I execute the `debuggables` command, the hover window is too horizontally small to display the entire names of the debuggables.

**Comment by GordianDziwis** [comment]
@retarpt You can globally override the floating preview config:

```lua
local border = { '▗', '▄', '▖', '▌', '▘', '▀', '▝', '▐' };

local orig_util_open_floating_preview = vim.lsp.util.open_floating_preview;
function vim.lsp.util.open_floating_preview(contents, syntax, opts, ...)
    opts = opts or {};
    opts.border = border;
    opts.max_width = opts.max_width or 100;
    opts.wrap = opts.wrap or true;
    return orig_util_open_floating_preview(contents, syntax, opts, ...);
end;
```

**Comment by retarpt** [comment]
Thank you very much!

**Comment by JeanMertz** [comment]
> [@mrcjkb](https://github.com/mrcjkb?rgh-link-date=2024-08-08T10%3A14%3A29.000Z) Is this config lazily evaluated on creation of a float?

With regards to this point, does this mean relative positioning to the right of the window is not possible, because we have to get the width of the window at runtime, and not when configuring the global Rustaceanvim float config?

**Comment by mrcjkb** [comment]
As of now, the only way to do that would be by overriding `vim.lsp.util.open_floating_preview`, I suppose.

**Comment by JeanMertz** [comment]
> As of now, the only way to do that would be by overriding `vim.lsp.util.open_floating_preview`, I suppose.

I did think about that, but because opening the float happens asynchronously, I don't believe I can dynamically change the float preview config for a single `rustaceanvim` call? E.g. this won't work?

```lua
-- override vim.lsp.util.open_floating_preview
vim.cmd.RustLsp({ "renderDiagnostic", "current" }) -- calls `open_floating_preview` in a scheduled task
-- revert to old vim.lsp.util.open_floating_preview
```

Or perhaps this _will_ work? I'll have to experiment with it.
