### ISSUE TITLE
Allow to store cargo output in quickfix list

### ISSUE THREAD

**Issue by jla2000** [mrcjkb/rustaceanvim#468]
### Feature description

When running e.g. `RustLsp runnables`, there should be an option to store the cargo output in the quickfix list. When the proper error format is set there, it would be possible to quickly jump to errors across the whole project. Since this is often the case e.g. when fighting the borrow checker, I feel like this is something really missing in the plugin currently.

**Comment by mrcjkb** [comment]
Hey :wave: 

This is already possible. See `:h rustaceanvim.config`, `:h rustaceanvim.tools.Opts` and `:h rustaceanvim.executor_alias`.

**Comment by jla2000** [comment]
Hi @mrcjkb thanks for the quick response :)
When I set the executor according to the docs, it will only print the runtime output, not the cargo compilation output.
The compilation output seems to be omitted.

**Comment by mrcjkb** [comment]
Just pushed a potential hotfix: https://github.com/mrcjkb/rustaceanvim/commit/44b74badad1b0a14c492fe8958f63586dd3acd06

If that doesn't solve it for you, then you can work around it by using a custom `:h rustaceanvim.Executor`.

**Comment by jla2000** [comment]
Unfortunately this did not fix the issue. Also it seems like that the whole runtime output of programs is put into a single line in the quickfix list. I will try it with `Executor`

**Comment by mrcjkb** [comment]
Just pushed another hotfix for the single line issue: https://github.com/mrcjkb/rustaceanvim/commit/7da155a907e3f48b1f7c25c59e248996fba833df

(this is an old executor carries over from rust-tools).

**Comment by zakissimo** [comment]
Any news about this? I'm very interested in this. Looking at the documentation, I came up with this config, but I don't have the expected behavior.

```lua
      {
        "mrcjkb/rustaceanvim",
        version = "^5",
        lazy = false,
        config = function()
          vim.g.rustaceanvim = {
            tools = {
              float_win_config = {
                border = "rounded",
              },
              executor = "quickfix",
            },
            server = {
              on_attach = require("config.utils.lsp").setup,
              default_settings = {
                ["rust-analyzer"] = {
                  cargo = {
                    allFeatures = true,
                    loadOutDirsFromCheck = true,
                    runBuildScripts = true,
                  },
                  procMacro = {
                    enable = true,
                    ignored = {
                      ["async-trait"] = { "async_trait" },
                      ["napi-derive"] = { "napi" },
                      ["async-recursion"] = { "async_recursion" },
                    },
                  },
                  inlayHints = {
                    lifetimeElisionHints = {
                      enable = true,
                      useParameterNames = true,
                    },
                  },
                },
              },
            },
          }
        end,
      },
```

Did I miss something?
