### ISSUE TITLE
Problems with proc_macros

### ISSUE THREAD

**Issue by renato145** [mrcjkb/rustaceanvim#480]
### Have you read the docs and searched existing issues?

- [X] I have read [the README's troubleshooting guide](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#stethoscope-troubleshooting) and FAQ(https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#left_speech_bubble-faq).
- [X] I am using the latest rustaceanvim release.
- [X] I have searched [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
- [X] I have searched [existing discussions](https://github.com/mrcjkb/rustaceanvim/discussions).
- [X] I have searched the existing issues of other plugins related to this issue (if applicable).
- [X] I have searched the [existing rust-analyzer issues](https://github.com/rust-lang/rust-analyzer/issues?q=is%3Aissue+) (if applicable).
- [X] I can reproduce the issue with stable Neovim (not a distribution or nightly) and the [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).

### Neovim version (nvim -v)

v0.11.0-dev

### Operating system/version

Ubuntu 22.04

### Output of :checkhealth rustaceanvim

```console
Checking for Lua dependencies ~
- OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 1.80.1 (3f5fd8d 2024-08-06)
- OK Cargo: found cargo 1.80.1 (376290515 2024-07-16)
- OK rustc: found rustc 1.80.1 (3f5fd8dd4 2024-08-06)
- OK debug adapter: found codelldb 

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- OK tree-sitter parser for Rust detected.
```

### How to reproduce the issue

```console
cargo new tmp-tst
On Cargo.toml add dependencies:

mongodb = "3.0"
tokio = { version = "1.39", features = ["macros", "rt-multi-thread"] }
futures = "0.3"
```

on main.rs:
```
use futures::StreamExt;
use mongodb::{
    bson::{doc, Document},
    Client,
};

#[tokio::main]
async fn main() {
    let client = Client::with_uri_str("mongodb://user:pass@localhost:27017/?directConnection=true")
        .await
        .unwrap();
    let result = client
        .database("some_db")
        .collection::<Document>("some_collection")
        .find(doc! {})
        .limit(5)
        .await
        .unwrap()
        .collect::<Vec<_>>()
        .await;
}
```
```


### Expected behaviour

The limit function should be recognized as well as the collect.

### Actual behaviour

No LSP definition is found for `limit`.
Calling `.await` on the result of find should result in a `Cursor` but that is not resolved.

### The minimal config used to reproduce this issue.

```Lua
vim.env.LAZY_STDPATH = '.repro'
load(vim.fn.system('curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua'))()

require('lazy.minit').repro {
  spec = {
    {
      'mrcjkb/rustaceanvim',
      version = '^5',
      init = function()
        -- Configure rustaceanvim here
        vim.g.rustaceanvim = {}
      end,
      lazy = false,
    },
  },
}
```

**Comment by mrcjkb** [comment]
Hey 👋 

This looks like a rust-analyzer issue to me.

**Comment by renato145** [comment]
Is it? It works correctly in vscode with default config :C

**Comment by mrcjkb** [comment]
Are you using the same rust-analyzer build?

rustaceanvim doesn't set any default configs besides enabling clippy if it's detected. 
And I doubt that there's a client capability related to proc macros.

It could also be that vscode explicitly enables a setting, so you could try playing around with the rust-analyzer configuration.

**Comment by renato145** [comment]
You are right, didnt know that `rustup component add rust-analyzer` gives an old version s:
