### ISSUE TITLE
Diagnostics aren't working for standalone files

### ISSUE THREAD

**Issue by h3xOo** [mrcjkb/rustaceanvim#489]
### Have you read the docs and searched existing issues?

- [X] I have read [the README's troubleshooting guide](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#stethoscope-troubleshooting) and FAQ(https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#left_speech_bubble-faq).
- [X] I am using the latest rustaceanvim release.
- [X] I have searched [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
- [X] I have searched [existing discussions](https://github.com/mrcjkb/rustaceanvim/discussions).
- [ ] I have searched the existing issues of other plugins related to this issue (if applicable).
- [ ] I have searched the [existing rust-analyzer issues](https://github.com/rust-lang/rust-analyzer/issues?q=is%3Aissue+) (if applicable).
- [X] I can reproduce the issue with stable Neovim (not a distribution or nightly) and the [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).

### Neovim version (nvim -v)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1723675123

### Operating system/version

Artix Linux (6.10.6-artix1-1)

### Output of :checkhealth rustaceanvim

```console
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- WARNING dap not installed. Needed for debugging features [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap)

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 1 (0f7f68dad2 2024-08-27)
- OK Cargo: found cargo 1.80.1 (376290515 2024-07-16)
- OK rustc: found rustc 1.80.1 (3f5fd8dd4 2024-08-06) (Arch Linux rust 1:1.80.1-1)

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- WARNING No tree-sitter parser for Rust detected. Required by 'Rustc unpretty' command.
```

### How to reproduce the issue

```console
mkdir -p /tmp/minimal
# get minimal.lua

create file `standalone.rs`, and place something like this in it

fn main() {
    println!("Hi mom");
    agagajghagjhgh
}

next go `nvim -u minimal.lua standalone.rs`. After some time garbage will have red undercurl/underline, and `:Inspect` will show unresolved reference, but diagnostic will not render, which you can confirm by `:lua vim.diagnostic.goto_next()`.

Funny enough, if you do same thing with cargo project (like `mkdir cargo-test && cd cargo-test && cargo init .`) and then `nvim -u ../minimal.lua src/main.rs`, diagnostic will appear.
```

### Expected behaviour

https://github.com/user-attachments/assets/534fb991-7ec2-4ed3-bcb8-df870c766a37

### Actual behaviour

https://github.com/user-attachments/assets/7e0e427c-2b05-4241-bb38-ab539d345ccf

### The minimal config used to reproduce this issue.

```Lua
vim.env.LAZY_STDPATH = '.repro'
load(vim.fn.system('curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua'))()

require('lazy.minit').repro {
  spec = {
    {
      'mrcjkb/rustaceanvim',
      version = '^5',
      init = function()
        -- Configure rustaceanvim here
        vim.g.rustaceanvim = {}
      end,
      lazy = false,
    },
  },
}
```

**Comment by mrcjkb** [comment]
Hey :wave: 

I just tried reproducing this with the minimal config you posted and it works fine on my end.

![scrot](https://github.com/user-attachments/assets/d0508598-f82c-47e0-b356-d92cab833ae3)

It must be an issue with your rust toolchain or rust-analyzer.
