### ISSUE TITLE
Rust analyzer does not respet rust-toolchain.toml

### ISSUE THREAD

**Issue by vaqxai** [mrcjkb/rustaceanvim#492]
### Have you read the docs and searched existing issues?

- [X] I have read [the README's troubleshooting guide](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#stethoscope-troubleshooting) and FAQ(https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#left_speech_bubble-faq).
- [X] I am using the latest rustaceanvim release.
- [X] I have searched [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
- [X] I have searched [existing discussions](https://github.com/mrcjkb/rustaceanvim/discussions).
- [ ] I have searched the existing issues of other plugins related to this issue (if applicable).
- [X] I have searched the [existing rust-analyzer issues](https://github.com/rust-lang/rust-analyzer/issues?q=is%3Aissue+) (if applicable).
- [X] I can reproduce the issue with stable Neovim (not a distribution or nightly) and the [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Ubuntu 24.04 (x86)

### Output of :checkhealth rustaceanvim

```console
==============================================================================
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.

Checking external dependencies ~
- WARNING No debug adapter detected. Make sure either lldb or codelldb is available on the path.
- OK rust-analyzer: found rust-analyzer 1.80.1 (3f5fd8d 2024-08-06)
- OK Cargo: found cargo 1.80.1 (376290515 2024-07-16)
- OK rustc: found rustc 1.80.1 (3f5fd8dd4 2024-08-06)

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- OK tree-sitter parser for Rust detected.
```

### How to reproduce the issue

```console
1. add a rust-toolchain.toml to a rust project
2. write [toolchain] and channel="nightly" in the next line into the file
3. add #[feature(portable_simd)] to your main.rs/lib.rs
```

### Expected behaviour

see no error in nvim

### Actual behaviour

i see a "`#![feature] may not be used on a stable release channel`" floating error, even though the compiler compiles fine

### The minimal config used to reproduce this issue.

```Lua
the default template you guys provide
```

P.S. the error is not shown in VSCode

**Comment by mrcjkb** [comment]
Hey 👋 

This is either an issue with your rust-analyzer installation or its configuration.

> P.S. the error is not shown in VSCode

This is likely because VSCode is not using the same build.
