### ISSUE TITLE
Add call jobstart to open_url function

### ISSUE THREAD

**Issue by h0pes** [mrcjkb/rustaceanvim#50]
### Feature description

Somehow on my `nvim` install neither `vim.fn.jobstart({ 'xdg-open', 'https://github.com' })` nor `vim.system({ 'xdg-open', 'https://github.com' })` work.

`xdg-open` works perfectly fine run directly from the terminal with a simple `xdg-open https://www.google.com`.

I can get it working from _nvim_ as an external command execution with `:!xdg-open <url>`.

I'm not able to understand how to fix this, but I found that the following command works:
`:call jobstart('xdg-open https://www.github.com')`

In order to use the `open_url(url)` function [here](https://github.com/mrcjkb/rustaceanvim/blob/64edff2b2ab8281afcc55f140303e357a35a649f/lua/rustaceanvim/commands/external_docs.lua#L6), would it be possible to add a case to run that command?

I find extremely useful the `RunLsp externalDocs` feature and I'd really like being able to use it.

By the way I attach the error I get when I try to run the `externalDocs` command.

Thanks a lot!
![2023-11-11_09-16_OpenExternalDocs](https://github.com/mrcjkb/rustaceanvim/assets/25418553/8ce630a3-5bca-4409-a187-0f08a73e87c0)

**Comment by mrcjkb** [comment]
Hey :wave: 

Thanks for reporting. That's actually a bug in this plugin - it's using a Neovim function that isn't available in Neovim 0.9 yet.
I'll fix that now...
