### ISSUE TITLE
No autocomplete/docs if I use io_uring crate

### ISSUE THREAD

**Issue by xbladesub** [mrcjkb/rustaceanvim#506]
my config:
```lua
{
			"mrcjkb/rustaceanvim",
			version = "^5",
			lazy = false,
			["rust-analyzer"] = {
				cargo = {
					allFeatures = true
				}
			}
		}
```

if I use io_uring crate:
<img width="988" alt="image" src="https://github.com/user-attachments/assets/0ba53a92-f6be-4279-89a2-b9fba3eacf8d">

if I don't:
<img width="991" alt="image" src="https://github.com/user-attachments/assets/ba582a8f-447a-4a36-a02e-696d140e6079">

**Comment by mrcjkb** [comment]
Hey :wave: 

rustaceanvim [doesn't implement autocompletion](https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#how-to-enable-auto-completion).
This is likely an issue with your rust project.

For future reference: Please use the [bug report template](https://github.com/mrcjkb/rustaceanvim/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml) for such issues.
It has a checklist + guides for troubleshooting and reproducing issues with a minimal config.
