### ISSUE TITLE
Report rust_analyzer issues when it fails to load the workspace

### ISSUE THREAD

**Issue by edevil** [mrcjkb/rustaceanvim#507]
### Feature description

When we make certain mistakes, such as declaring a dependency in a wrong way, rust_analyzer fails to load the workspace and most of the LSP stuff stops working silently. We don't get any warning/notification that this has happened.

In VsCode there is a button that turns red, and when we click it we can see the rust_analyzer logs.
![Screenshot 2024-09-10 at 15 31 57](https://github.com/user-attachments/assets/a0fb34c5-ab3e-470d-af53-1f9112083fb4)

Using rustaceanvim I can also look at the logs using `:RustLsp logFile`, which indeed indicates some error:
```
2024-09-18T11:20:43.934992Z ERROR rust_analyzer::main_loop: FetchWorkspaceError:rust-analyzer failed to load workspace: Failed to load the project at /Users/acruz...
```
the thing is I don't know that there is an issue. It would be great if these kind of errors showed some form of notification that would compel us to look at the log file.

**Comment by mrcjkb** [comment]
Sounds like a good idea :smile:

**Comment by edevil** [comment]
Thanks!
