### ISSUE TITLE
`client.supports_method("textDocument/rename")` returns `false`

### ISSUE THREAD

**Issue by JeanMertz** [mrcjkb/rustaceanvim#521]
### Have you read the docs and searched existing issues?

- [X] I have read [the README's troubleshooting guide](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#stethoscope-troubleshooting) and FAQ(https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#left_speech_bubble-faq).
- [X] I am using the latest rustaceanvim release.
- [X] I have searched [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
- [X] I have searched [existing discussions](https://github.com/mrcjkb/rustaceanvim/discussions).
- [X] I have searched the existing issues of other plugins related to this issue (if applicable).
- [X] I have searched the [existing rust-analyzer issues](https://github.com/rust-lang/rust-analyzer/issues?q=is%3Aissue+) (if applicable).
- [X] I can reproduce the issue with stable Neovim (not a distribution or nightly) and the [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).

### Neovim version (nvim -v)

NVIM v0.11.0-nightly+e820474

### Operating system/version

macOS 14.5

### Output of :checkhealth rustaceanvim

```console
==============================================================================
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 1.80.0 (05147895 2024-07-21)
- OK Cargo: found cargo 1.80.0 (376290515 2024-07-16)
- OK rustc: found rustc 1.80.0 (051478957 2024-07-21)
- OK debug adapter: found codelldb 

Checking config ~
- ERROR vim.g.rustaceanvim is set, but it was sourced after rustaceanvim was initialized.
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- OK tree-sitter parser for Rust detected.
```

_NOTE: I'm aware of the load order error, I haven't found the solution yet (using Nix to load my plugins), but I this to have an impact on this issue_

### Expected behaviour

I have (among other code) this in my `on_attach` function:

```lua
if client.supports_method("textDocument/rename") then
    -- ... keymap for regular vim.lsp.buf.rename (NOT RA's structural rename)
end
```

For Rust buffers, the keymap wasn't available, while this worked for other LSPs. After debugging, I found that `client.supports_method("textDocument/rename")` returns `false`.

However, if I just set the keymap without the check, the rename feature works as expected.

**Comment by mrcjkb** [comment]
Hey :wave: 

rustaceanvim doesn't set these properties. It's likely a rust-analyzer issue.

**Comment by JeanMertz** [comment]
My bad. I assumed that this was asking the “client” for its feature set, which I then assumed was this plugin, as opposed to RA being the server.

I’ll bring it up at the RA issue tracker instead.

**Comment by mrcjkb** [comment]
You can configure the client to tell the server which capabilities it supports, which rustaceanvim does (the `textDocument/rename` cabability is one of Neovim's default capabilities).
But not all servers support all client capabilities, so when starting up, the server communicates to the client which ones it supports, which you can then query with `client.supports_method`.
