### ISSUE TITLE
Add support for neoconf

### ISSUE THREAD

**Issue by mrcjkb** [mrcjkb/rustaceanvim#53]
### Discussed in https://github.com/mrcjkb/rustaceanvim/discussions/49

<div type='discussions-op-text'>

<sup>Originally posted by **TD-Sky** November 11, 2023</sup>
I use `.neoconf.json` to configure rust-analyzer locally. Now I cannot setup LSP client via `nvim-lspconfig` as rustaceanvim will do it. So are there any other ways to pass the project local settings?</div>

Note: rust-analyzer settings [can be dynamically loaded from a `rust-analyzer.json` file](https://github.com/mrcjkb/rustaceanvim#how-to-dynamically-load-different-rust-analyzer-settings-per-project), without neoconf.

**Comment by TD-Sky** [comment]
I am the original discussion questioner. Now I'm using `exrc` released at nvim 0.9 instead of `neoconf.json`.

**Comment by mrcjkb** [comment]
> I am the original discussion questioner. Now I'm using `exrc` released at nvim 0.9 instead of `neoconf.json`.

Oh yeah, I forgot that was added - and works well with `vim.g` configs...

I guess that means there isn't really strong a use case for this plugin supporting neoconf right now (this plugin requires nvim >= 0.9).

**Comment by Alt-iOS** [comment]
Hi, where do you put the init.lua to simulate the neoconf config? I tried on the project folder but it gets ignored or how do you do it with `exrc`, I am relatively new and can't for the life of me figure out where to put a file to config local projects

```toml
vim.g.rustaceanvim = {
  -- Plugin configuration
  tools = {
  },
  -- LSP configuration
  server = {
    on_attach = function(client, bufnr)
      -- you can also put keymaps in here
    end,
    default_settings = {
      -- rust-analyzer language server configuration
      ['rust-analyzer'] = {
        ['rust-analyzer.rust.analyzerTargetDir'] = true,
        ['rust-analyzer.rustfmt.overrideCommand'] = { "leptosfmt", "--stdin", "--rustfmt" },
        -- Additional settings appended here
        cargo = {
          allFeatures = true,
          loadOutDirsFromCheck = true,
          runBuildScripts = true,
        },
        checkOnSave = {
          allFeatures = true,
          command = "clippy",
          extraArgs = { "--no-deps" },
        },
        procMacro = {
          enable = true,
          ignored = {
            ["async-trait"] = { "async_trait" },
            ["napi-derive"] = { "napi" },
            ["async-recursion"] = { "async_recursion" },
          },
        },
      },
    },
  },
  -- DAP configuration
  dap = {
  },
}
```

**Comment by mrcjkb** [comment]
> Hi, where do you put the init.lua to simulate the neoconf config? I tried on the project folder but it gets ignored or how do you do it with `exrc`, I am relatively new and can't for the life of me figure out where to put a file to config local projects
> 
> ```toml
> vim.g.rustaceanvim = {
>   -- Plugin configuration
>   tools = {
>   },
>   -- LSP configuration
>   server = {
>     on_attach = function(client, bufnr)
>       -- you can also put keymaps in here
>     end,
>     default_settings = {
>       -- rust-analyzer language server configuration
>       ['rust-analyzer'] = {
>         ['rust-analyzer.rust.analyzerTargetDir'] = true,
>         ['rust-analyzer.rustfmt.overrideCommand'] = { "leptosfmt", "--stdin", "--rustfmt" },
>         -- Additional settings appended here
>         cargo = {
>           allFeatures = true,
>           loadOutDirsFromCheck = true,
>           runBuildScripts = true,
>         },
>         checkOnSave = {
>           allFeatures = true,
>           command = "clippy",
>           extraArgs = { "--no-deps" },
>         },
>         procMacro = {
>           enable = true,
>           ignored = {
>             ["async-trait"] = { "async_trait" },
>             ["napi-derive"] = { "napi" },
>             ["async-recursion"] = { "async_recursion" },
>           },
>         },
>       },
>     },
>   },
>   -- DAP configuration
>   dap = {
>   },
> }
> ```

Hey 😃
exrc is disabled by default.
You need to set `vim.opt.exrc = true` in your init.lua to enable it.

**Comment by Alt-iOS** [comment]
Heeey!!, thanks a lot!!, just tried it but sadly still didnt work :(, in your project in the main folder is where you put another init.lua or is the file name diferent? 🥲, the code formatter from nvim still isnt working (while invoking via cmd does actually work) Do you know what else can I try?

**Comment by mrcjkb** [comment]
> Heeey!!, thanks a lot!!, just tried it but sadly still didnt work :(, in your project in the main folder is where you put another init.lua or is the file name diferent? 🥲, the code formatter from nvim still isnt working (while invoking via cmd does actually work) Do you know what else can I try?
> 
> EDIT: in case anyone sees it, it was .nvim.lua but the config up there still wrong, it doesnt do anything

Please see `:help 'exrc'`.

Based on your edit and the issue you opened, I presume you got it working (but leptosfmt is not working for you?)

You should change this bit:

```lua
['rust-analyzer'] = {
        ['rust-analyzer.rust.analyzerTargetDir'] = true,
        ['rust-analyzer.rustfmt.overrideCommand'] = { "leptosfmt", "--stdin", "--rustfmt" },
```

to

```lua
['rust-analyzer'] = {
        ['rust.analyzerTargetDir'] = true,
        ['rustfmt.overrideCommand'] = { "leptosfmt", "--stdin", "--rustfmt" },
```

Otherwise your resulting configuration keys will be `rust-analyzer.rust-analyzer.*`
