### ISSUE TITLE
FR: Show any kind of warning when your .vscode/settings.json is JSON5 but invalid JSON

### ISSUE THREAD

**Issue by cormacrelf** [mrcjkb/rustaceanvim#537]
### Feature description

VSCode supports comments in its JSON configuration because it supports JSON5. rustaceanvim does not. If you have any comments or trailing commas etc, rustaceanvim cannot decode the JSON, and is completely silent about it.

This is a bit of a concern because comments are very common in VSCode configurations, and since the other methods are deprecated, this is now the only way to configure rustaceanvim. It should show a warning, and it should perhaps also **optionally** support JSON5 (e.g. using <https://github.com/Joakker/lua-json5>).

**Comment by mrcjkb** [comment]
Hey :wave: 

thanks for the heads-up. I'll look into it soon.
