### ISSUE TITLE
Codelldb rust debug formatter does not work

### ISSUE THREAD

**Issue by mateusz2173** [mrcjkb/rustaceanvim#552]
### Have you read the docs and searched existing issues?

- [X] I have read [the README's troubleshooting guide](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#stethoscope-troubleshooting) and FAQ(https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#left_speech_bubble-faq).
- [X] I am using the latest rustaceanvim release.
- [X] I have searched [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
- [X] I have searched [existing discussions](https://github.com/mrcjkb/rustaceanvim/discussions).
- [X] I have searched the existing issues of other plugins related to this issue (if applicable).
- [X] I have searched the [existing rust-analyzer issues](https://github.com/rust-lang/rust-analyzer/issues?q=is%3Aissue+) (if applicable).
- [X] I can reproduce the issue with stable Neovim (not a distribution or nightly) and the [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).
- [X] This is an issue about rustaceanvim, not rust-analyzer or Neovim.
- [X] This is [not an issue with autocompletion](https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#im-having-issues-with-autocompletion).

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

MacOS 15.1

### Output of :checkhealth rustaceanvim

```console
==============================================================================
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 1.82.0 (f6e511ee 2024-10-15)
- OK Cargo: found cargo 1.82.0 (8f40fc59f 2024-08-21)
- OK rustc: found rustc 1.82.0 (f6e511eec 2024-10-15)
- OK debug adapter: found codelldb 

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- OK tree-sitter parser for Rust detected.
```

### How to reproduce the issue

```console
:MasonInstall codelldb
:DapToggleBreakpoint # toggle breakpoint somewhere in rust code so debugger won't exit too quickly
:RustLsp debug
```

### Expected behaviour

Rust data structures are formatted correctly by debugger, e.g. String variable should show actual text instead internal representation, that it, it should be formatted.

### Actual behaviour

<img width="368" alt="Screenshot 2024-10-24 at 14 08 39" src="https://github.com/user-attachments/assets/8c708926-f8be-4782-9754-2a9dff74af2b">

Rust data structures / primitives are not formatted correctly; dap adapter outputs formatter error:

```
[debug-adapter stderr] ERROR(Python) 13:57:42 formatters.rust: ('ReadMemory error: %s', 'SBProcess is invalid')
Traceback (most recent call last):
  File "/Users/morphe/.local/share/nvim/mason/packages/codelldb/extension/formatters/rust.py", line 116, in get_synth_summary
    summary = RustSynthProvider.synth_by_id[obj_id].get_summary()
  File "/Users/morphe/.local/share/nvim/mason/packages/codelldb/extension/formatters/rust.py", line 357, in get_summary
    strval = string_from_ptr(self.ptr, min(self.len, max_string_summary_langth))
  File "/Users/morphe/.local/share/nvim/mason/packages/codelldb/extension/formatters/rust.py", line 147, in string_from_ptr
    raise Exception('ReadMemory error: %s', error.GetCString())
Exception: ('ReadMemory error: %s', 'SBProcess is invalid')
```

It's worth mentioning using the same verison of codelldb works correctly in Visual Studio Code.

### The minimal config used to reproduce this issue.

```Lua
-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
	local lazyrepo = "https://github.com/folke/lazy.nvim.git"
	local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
	if vim.v.shell_error ~= 0 then
		vim.api.nvim_echo({
			{ "Failed to clone lazy.nvim:\n", "ErrorMsg" },
			{ out, "WarningMsg" },
			{ "\nPress any key to exit..." },
		}, true, {})
		vim.fn.getchar()
		os.exit(1)
	end
end
vim.opt.rtp:prepend(lazypath)

-- Make sure to setup `mapleader` and `maplocalleader` before
-- loading lazy.nvim so that mappings are correct.
-- This is also a good place to setup other settings (vim.opt)
vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

-- Setup lazy.nvim
require("lazy").setup({
	spec = {
		-- add your plugins here
		{ 
			'williamboman/mason.nvim',
			config = function ()
				require('mason').setup()
			end
		},
		{ 
			'mfussenegger/nvim-dap',
			dependencies = { 'rcarriga/nvim-dap-ui', 'nvim-neotest/nvim-nio' },
			config = function ()
				local dap, dapui = require("dap"), require("dapui")

				dapui.setup()

				dap.listeners.before.attach.dapui_config = function()
					dapui.open()
				end
				dap.listeners.before.launch.dapui_config = function()
					dapui.open()
				end
				dap.listeners.before.event_terminated.dapui_config = function()
					dapui.close()
				end
				dap.listeners.before.event_exited.dapui_config = function()
					dapui.close()
				end
			end
		},
		{ 'mrcjkb/rustaceanvim' },
	},
})
```
```

**Comment by mrcjkb** [comment]
hey 👋 

rustaceanvim just sets up the nvim-dap configuration for you. It doesn't do any formatting.

This is an issue with either nvim-dap, nvim-dap-ui or the  codelldb package installed using mason.

**Comment by mateusz2173** [comment]
It looks like Codelldb dropped rust formatter support in latest version 

https://github.com/vadimcn/codelldb/blob/master/CHANGELOG.md

> To reduce the maintenance burden, support for the Rust language service and custom data formatters in CodeLLDB has been removed. The constant breaking changes in LLDB's language service API, along with Rust's evolving internal representation of std:: types, have made it increasingly difficult to maintain these updates. Future versions of CodeLLDB will be based on stock LLDB, without the Rust language service. Rust data types will still have partial support via the data formatters provided by rustc, but custom formatters will no longer be maintained.

**Comment by chaozwn** [comment]
> @mrcjkb It looks like Codelldb dropped rust formatter support in latest version
> 
> https://github.com/vadimcn/codelldb/blob/master/CHANGELOG.md
> 
> > To reduce the maintenance burden, support for the Rust language service and custom data formatters in CodeLLDB has been removed. The constant breaking changes in LLDB's language service API, along with Rust's evolving internal representation of std:: types, have made it increasingly difficult to maintain these updates. Future versions of CodeLLDB will be based on stock LLDB, without the Rust language service. Rust data types will still have partial support via the data formatters provided by rustc, but custom formatters will no longer be maintained.

so, any solution for this, now i can't  check String value in debug.

**Comment by mateusz2173** [comment]
@chaozwn 
Fortunately, there is a fresh solution
https://github.com/cmrschwarz/rust-prettifier-for-lldb/

**Comment by chaozwn** [comment]
> @chaozwn Fortunately, there is a fresh solution https://github.com/cmrschwarz/rust-prettifier-for-lldb/

thanks.

**Comment by chaozwn** [comment]
> @chaozwn Fortunately, there is a fresh solution https://github.com/cmrschwarz/rust-prettifier-for-lldb/

works well. thanks.

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "demo",
      "type": "codelldb",
      "request": "launch",
      "program": "${workspaceFolder}/target/debug/${workspaceFolderBasename}",
      "mode": "debug",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "preLaunchTask": "cargo build",
      "externalConsole": true,
      "expressions": "simple",
      "preRunCommands": [
        "command script import ~/.local/share/nvim/lazy/rust-prettifier-for-lldb/rust_prettifier_for_lldb.py"
      ]
    },
    {
      "name": "tauri backend",
      "type": "codelldb",
      "request": "launch",
      "program": "${workspaceFolder}/src-tauri/target/debug/${workspaceFolderBasename}",
      "mode": "debug",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}/src-tauri",
      "environment": [],
      "preLaunchTask": "tauri backend build",
      "externalConsole": true,
      "expressions": "simple",
      "preRunCommands": [
        "command script import ~/.local/share/nvim/lazy/rust-prettifier-for-lldb/rust_prettifier_for_lldb.py"
      ]
    },
    {
      "name": "tauri development debug",
      "type": "codelldb",
      "request": "launch",
      "program": "${workspaceFolder}/src-tauri/target/debug/${workspaceFolderBasename}",
      "cwd": "${workspaceFolder}",
      "mode": "debug",
      // task for the `beforeDevCommand` if used, must be configured in `.vscode/tasks.json`
      "preLaunchTask": "ui:dev"
    },
    {
      "name": "tauri production debug",
      "type": "codelldb",
      "request": "launch",
      "program": "${workspaceFolder}/target/debug/${workspaceFolderBasename}",
      "mode": "debug",
      // task for the `beforeBuildCommand` if used, must be configured in `.vscode/tasks.json`
      "preLaunchTask": "ui:build"
    }
  ]
```
