### ISSUE TITLE
`textDocument/hover` got deprecated (nightly nvim) 

### ISSUE THREAD

**Issue by NicolasGB** [mrcjkb/rustaceanvim#556]
### Feature description

Hi!

As of yesterday `vim.lsp.hover` globally got deprecated: https://github.com/neovim/neovim/pull/30935

Resulting in loosing the classic "rustaceanvim" code actions (with the numbers etc).

Here's an example of the current hover output with nightly:
![image](https://github.com/user-attachments/assets/583133e8-0396-40aa-b77a-cce16752eb55)

It looks like hover's cannot be set globally anymore, for example now my keybinding is:

```lua
          vim.keymap.set("n", "K", function() vim.lsp.buf.hover({border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" }}) end, opts)
```
Let me know if i can provide any more information. 

Feel free to classify this as a bug if you consider it right. I wasn't really sure

**Comment by mrcjkb** [comment]
hey 👋 

Thanks for reporting. Given that there appears to be no alternative way of overriding the built-in hover callback for a client, I guess you'll have to use `:RustLsp hover actions` (which you can invoke with a keymap).

**Comment by NicolasGB** [comment]
Oh yeah i see.  

Thanks for your answer!
