### ISSUE TITLE
no diagnostics for examples with some repositories

### ISSUE THREAD

**Issue by TomzBench** [mrcjkb/rustaceanvim#562]
### Have you read the docs and searched existing issues?

- [X] I have read [the README's troubleshooting guide](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#stethoscope-troubleshooting) and FAQ(https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#left_speech_bubble-faq).
- [X] I am using the latest rustaceanvim release.
- [X] I have searched [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
- [X] I have searched [existing discussions](https://github.com/mrcjkb/rustaceanvim/discussions).
- [X] I have searched the existing issues of other plugins related to this issue (if applicable).
- [X] I have searched the [existing rust-analyzer issues](https://github.com/rust-lang/rust-analyzer/issues?q=is%3Aissue+) (if applicable).
- [X] I can reproduce the issue with stable Neovim (not a distribution or nightly) and the [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).
- [X] This is an issue about rustaceanvim, not rust-analyzer or Neovim.
- [X] This is [not an issue with autocompletion](https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#im-having-issues-with-autocompletion).

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

Windows 11 Pro for workstations

### Output of :checkhealth rustaceanvim

```console
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 0.3.2172-standalone (a341d598d 2024-11-04)
- OK Cargo: found 
- OK rustc: found 
- OK debug adapter: found codelldb 

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- OK tree-sitter parser for Rust detected.
- OK .vscode/settings.json loaded without errors.
```

### How to reproduce the issue

```console
mkdir ~/test
cd test
git clone -b no-diagnostics git@github.com:tomzbench/comport
nvim -u minimal.lua
:e src/lib.rs
:split examples/scan.rs
```

### Expected behaviour

I expect diagnostic to render on both examples/scan.rs and examples/lib.rs

**NOTE** that I tried to produce a minimal repository with this issue. However, a simple library crate with examples works like I would expect. I have not been able to discover what is unique with my repository that seems to prevent diagnostics from rendering in the examples.

**NOTE** that I do not know if this is issue with rust-analyzer or rustaceanvim so I clicked the checkbox assuming it is issue with rustaceanvim so that I can submit the issue. I hope that is ok.

### Actual behaviour

```rust
// examples/scan.rs
use foo; /* expect diagnostics here */
```
```rust
// src/lib.rs
use foo;  <=== remove it entirely  // works as expected
```
![image](https://github.com/user-attachments/assets/2f8800bf-a748-457a-bb78-2b95363cf9bd)

### The minimal config used to reproduce this issue.

```Lua
I use `minimal.lua` from the rustaceanvim repository verbatim
```

**Comment by mrcjkb** [comment]
Hey 👋 

This is because rust-analyzer has very limited support for standalone files that aren't part of a cargo project. 
Most of the diagnostics come from cargo, which requires a project.

**Comment by TomzBench** [comment]
Hi @mrcjkb 

Is the example not part of a cargo project?  The `examples` folder is explicitly understood by Cargo.

**Comment by mrcjkb** [comment]
> Is the example not part of a cargo project? The examples folder is explicitly understood by Cargo.

No. The repo is a cargo project, but `examples` is not a standard source directory and there's no configuration of it as such in the Cargo.toml.
rust-analyzer can't infer that. 

In any case, this has nothing to do with rustaceanvim, as it's a rust-analyzer issue.

**Comment by TomzBench** [comment]
I opened a tokio repository and added some bad code in a file under tokio/examples and I am able to see a diagnostics overlay.  So something in my repo is bugging up something (rust-analyzer or otherwise).
