### ISSUE TITLE
Semantic tokens highlight

### ISSUE THREAD

**Issue by ViniiR** [mrcjkb/rustaceanvim#575]
is there any way I can easily disable semantic tokens for rust specifically? they completely override any previous highlight I had and that only became an issue after using rustaceanvim, I believe rust-tools didn't have this functionality back when I created my theme, the reason I'd like to remove them is because not only I'd need to manually double the amount of highlight groups in my config I'd also lose information since for example it doesn't diferente between regular variables and constants when passing them as arguments to a function, it simply paints both of them white...

![IMG-20241111-WA0000](https://github.com/user-attachments/assets/aeea2592-8b67-4b2b-8cf2-fb6e9158a0b0)

**Comment by mrcjkb** [comment]
Closing as duplicate:

- https://github.com/search?q=repo%3Amrcjkb%2Frustaceanvim+semantic+tokens&type=discussions
