### ISSUE TITLE
Spam of "server cancelled the request" from rust-analyzer

### ISSUE THREAD

**Issue by edevil** [mrcjkb/rustaceanvim#580]
### Have you read the docs and searched existing issues?

- [X] I have read [the README's troubleshooting guide](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#stethoscope-troubleshooting) and FAQ(https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#left_speech_bubble-faq).
- [X] I am using the latest rustaceanvim release.
- [X] I have searched [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
- [X] I have searched [existing discussions](https://github.com/mrcjkb/rustaceanvim/discussions).
- [X] I have searched the existing issues of other plugins related to this issue (if applicable).
- [X] I have searched the [existing rust-analyzer issues](https://github.com/rust-lang/rust-analyzer/issues?q=is%3Aissue+) (if applicable).
- [ ] I can reproduce the issue with stable Neovim (not a distribution or nightly) and the [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).
- [X] This is an issue about rustaceanvim, not rust-analyzer or Neovim.
- [X] This is [not an issue with autocompletion](https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#im-having-issues-with-autocompletion).

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

MacOS

### Output of :checkhealth rustaceanvim

```console
==============================================================================
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 0.0.0 (8eef1c527 2024-10-25)
- OK Cargo: found cargo 1.82.0 (8f40fc59f 2024-08-21)
- OK rustc: found rustc 1.82.0 (f6e511eec 2024-10-15)
- OK debug adapter: found codelldb 

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- OK tree-sitter parser for Rust detected.
- OK .vscode/settings.json loaded without errors.
```

### How to reproduce the issue

Ever since https://github.com/rust-lang/rust-analyzer/commit/8eef1c52757f1ca444792b22433e696364a2b86d I get spammed whenever I'm editing a Rust file.

Issues have been reported for neovim (https://github.com/neovim/neovim/issues/30985), RA (https://github.com/rust-lang/rust-analyzer/issues/18434), but it's hard for me to tell exactly where the problem lies, or if we should just ignore this message.

Please close this ticket if this is not an issue with rustaceanvim.

### Expected behaviour

No messages.

### Actual behaviour

<img width="480" alt="Screenshot 2024-11-13 at 16 52 57" src="https://github.com/user-attachments/assets/1d95a04c-513b-45e7-a0bd-34788b003f36">

### The minimal config used to reproduce this issue.

```Lua
Lazyvim with the latest rustaceanvim, and an RA version that includes the patch above.
```

**Comment by mrcjkb** [comment]
hey 👋 

thanks for reporting. 

> Lazyvim with the latest rustaceanvim, and an RA version that includes the patch above.

LazyVim is not a minimal config (I have unchecked the respective checkbox).
Please read the troubleshooting guide and ensure this is reproducible with a minimal config, with exact steps to reproduce (including creating a rust project or file).
I'm afraid I don't have the capacity to follow up on issues that don't follow the steps outlined in the template.

**Comment by edevil** [comment]
Yeah, it shouldn't be an issue with this plugin. Sorry for the noise. :)

**Comment by bas-ie** [comment]
Just adding a note that this appears to have been fixed in nvim nightly, just upgraded and things are much better :heart:
