### ISSUE TITLE
Regression: Neotest adapter diagnostics started including color codes in the test failure output

### ISSUE THREAD

**Issue by ketchupfriend** [mrcjkb/rustaceanvim#609]
### Have you read the docs and searched existing issues?

- [X] I have read [the README's troubleshooting guide](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#stethoscope-troubleshooting) and FAQ(https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#left_speech_bubble-faq).
- [X] I am using the latest rustaceanvim release.
- [X] I have searched [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
- [X] I have searched [existing discussions](https://github.com/mrcjkb/rustaceanvim/discussions).
- [ ] I have searched the existing issues of other plugins related to this issue (if applicable).
- [ ] I have searched the [existing rust-analyzer issues](https://github.com/rust-lang/rust-analyzer/issues?q=is%3Aissue+) (if applicable).
- [X] I can reproduce the issue with stable Neovim (not a distribution or nightly) and the [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).
- [X] This is an issue about rustaceanvim, not rust-analyzer or Neovim.
- [X] This is [not an issue with autocompletion](https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#im-having-issues-with-autocompletion).

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

macOS

### Output of :checkhealth rustaceanvim

```console
==============================================================================
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- WARNING dap not installed. Needed for debugging features [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap)

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 1.83.0 (90b35a62 2024-11-26)
- OK Cargo: found cargo 1.83.0
- OK rustc: found rustc 1.83.0 (90b35a623 2024-11-26) (Homebrew)

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- WARNING No tree-sitter parser for Rust detected. Required by 'Rustc unpretty' command.
- OK .vscode/settings.json loaded without errors.
```

### How to reproduce the issue

```console
I have provided minimal_init.lua and main.rs in the minimal config section, but just want to note there is really nothing special about the setup. On my personal config on any Rust project, I was able to observe the problem.

nvim -u minimal_init.lua main.rs
:Neotest run
```

### Expected behaviour

Plain diagnostic message should be output:
<img width="1172" alt="image" src="https://github.com/user-attachments/assets/4dcc1eeb-d1e4-4598-ae13-7de9428d679b">

```
Diagnostics:
1. assertion `left == right` failed
     left: 1
    right: 2
   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

This is the behaviour with `    commit = "8ece53be36515cb9e76f3d03511643636469502d",`.

### Actual behaviour

Behaviour has regressed from an earlier version of rustaceanvim. Color code is included in the diagnostic message, which makes it hard to read:
<img width="1950" alt="image" src="https://github.com/user-attachments/assets/75f1c045-ed1f-4e63-9279-114d6c3f415d">

```
Diagnostics:
1. [31;1massertion `left == right` failed[0m
     left: 1
    right: 2
   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
   [0m
   
[2K------------
...
```

I believe this is a regression in rustaceanvim because reverting to `8ece53be36515cb9e76f3d03511643636469502d` restores the clean output.

### The minimal config used to reproduce this issue.

```Lua
# The minimal_init.lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
    spec = {
        {
            'mrcjkb/rustaceanvim',
            version = '^5', -- Recommended
            lazy = false, -- This plugin is already lazy
        },

        {
            "nvim-neotest/neotest",
            dependencies = {
                "nvim-neotest/nvim-nio",
                "nvim-lua/plenary.nvim",
                "antoinemadec/FixCursorHold.nvim",
                "nvim-treesitter/nvim-treesitter"
            },
            keys = {
                {
                    " tts",
                    function()
                        require("neotest").summary.toggle()
                    end,
                    desc = "[t]oggle [t]est [s]ummary",
                },
            },
        },
    },
})

require("neotest").setup({
    adapters = {
        require("rustaceanvim.neotest"),
    },
})


# main.rs
fn main() {
    println!("Hello, world!");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn always_fails() {
        assert_eq!(1, 2);
    }
}
```

**Comment by mrcjkb** [comment]
Hey :wave: 

I cannot reproduce this (neither with my config nor with the minimal config you posted).
There also haven't been any changes related to neotest since the commit you are referencing (which points to the 5.14.1 release).

Rustaceanvim passes `--color=never` when using Cargo.
I can reproduce the behaviour with cargo-nextest, so perhaps a recent change to cargo-nextest is the cause.
Are you using cargo-nextest by any chance?

**Comment by ketchupfriend** [comment]
I didn't configure nextest manually, but I dumped the args that `rustaceanvim` is using and it seems like it's deferring to nextest since I have it installed. This is on 5.18.0 that you just released (and it fixes the issue):
```
15:07:21 msg_show.echo ARGS
15:07:21 msg_show { "nextest", "--color", "never", "run", "--no-fail-fast", "--package", "sample", "--bin", "sample", "--", "tests" }
```

I think this is the default behaviour btw according to the docs:
```
        {enable_nextest?}                    (boolean)
                                                                                                               Whether to enable nextest. If enabled, `cargo test` commands will be transformed to `cargo nextest run` commands.
                                                                                                               Defaults to `true` if cargo-nextest is detected. Ignored if `cargo_override` is set.
```

I wonder if it might be helpful to have the resolved `cargo test` command in the `checkhealth` for the plugin, to help in future debugging?

Appreciate the quick fix!
