### ISSUE TITLE
Support `blink.cmp` LSP capabilities

### ISSUE THREAD

**Issue by unlimitedsola** [mrcjkb/rustaceanvim#615]
### Feature description

It would be nice if we could support inheriting [`blink.cmp`](https://github.com/Saghen/blink.cmp)'s LSP capabilities as well.

Please see [this comment](https://github.com/Saghen/blink.cmp/issues/476#issuecomment-2543343666) for more background.

I'm planning to make a PR for this. In the mean time, please let me know if you have any opinion on how this should be implemented. Thanks!

**Comment by mrcjkb** [comment]
hey 👋 

Sure, PRs are welcome.
[This is where rustaceanvim auto-registers plugin capabilities](https://github.com/mrcjkb/rustaceanvim/blob/1575af595130ea0f3563f737221c8e36c664d7b4/lua/rustaceanvim/config/server.lua#L136).

That being said, when Nvim 0.11 is released, I will likely remove that feature in favour of [`vim.lsp.config`](https://github.com/neovim/neovim/pull/3103), which will provide an official interface for such things.

**Comment by unlimitedsola** [comment]
> Sure, PRs are welcome. [This is where rustaceanvim auto-registers plugin capabilities](https://github.com/mrcjkb/rustaceanvim/blob/1575af595130ea0f3563f737221c8e36c664d7b4/lua/rustaceanvim/config/server.lua#L136).

Thank you for pointing that out, the PR is now available at https://github.com/mrcjkb/rustaceanvim/pull/616

> That being said, when Nvim 0.11 is released, I will likely remove that feature in favour of [`vim.lsp.config`](https://github.com/neovim/neovim/pull/3103), which will provide an official interface for such things.

That's definitely a good direction to which we should look forward. It should also solve this particular kind of integration issue once and for all, which is definitely a good thing!
