### ISSUE TITLE
`RustLsp runnables last` doesn't work

### ISSUE THREAD

**Issue by jimzk** [mrcjkb/rustaceanvim#62]
### Neovim version (nvim -v)

v0.9.4

### Operating system/version

macOS

### Output of `:checkhealth rustaceanvim`

```
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 0.3.1730-standalone (416e9c856 2023-11-12)
- OK Cargo: found cargo 1.73.0 (9c4383fb5 2023-08-26)
- OK rustc: found rustc 1.73.0 (cc66ad468 2023-10-03)
- OK lldb: found lldb-1500.0.22.8

Checking config ~
- OK vim.g.rustaceanvim is set
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.
```

### How to reproduce the issue

1. run a test by `RustLsp runnables`
2. execute `RustLsp runnables last`

### Expected behaviour

`RustLsp runnables last` should run the last running task

### Actual behaviour

Nothing happened

### The minimal config used to reproduce this issue.

N/A

**Comment by mrcjkb** [comment]
Hey :wave:

Thanks for reporting! I'm about to release a fix :smile:
