### ISSUE TITLE
Linting fails when clippy finds an error in a dependency

### ISSUE THREAD

**Issue by WhiteBlackGoose** [mrcjkb/rustaceanvim#625]
### Have you read the docs and searched existing issues?

- [X] I have read [the README's troubleshooting guide](https://github.com/mrcjkb/rustaceanvim/blob/master/README.md#stethoscope-troubleshooting) and FAQ(https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#left_speech_bubble-faq).
- [X] I am using the latest rustaceanvim release.
- [X] I have searched [existing issues](https://github.com/mrcjkb/rustaceanvim/issues?q=is%3Aopen+is%3Aissue+label%3Abug).
- [X] I have searched [existing discussions](https://github.com/mrcjkb/rustaceanvim/discussions).
- [X] I have searched the existing issues of other plugins related to this issue (if applicable).
- [X] I have searched the [existing rust-analyzer issues](https://github.com/rust-lang/rust-analyzer/issues?q=is%3Aissue+) (if applicable).
- [X] I can reproduce the issue with stable Neovim (not a distribution or nightly) and the [minimal config](https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua).
- [X] This is an issue about rustaceanvim, not rust-analyzer or Neovim.
- [X] This is [not an issue with autocompletion](https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#im-having-issues-with-autocompletion).

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

NixOS unstable

### Output of :checkhealth rustaceanvim

```console
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- WARNING dap not installed. Needed for debugging features [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap)

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 1.81.0-nightly (6292b2a 2024-07-02)
- OK Cargo: found cargo 1.81.0-nightly (4ed7bee47 2024-06-25)
- OK rustc: found rustc 1.81.0-nightly (6292b2af6 2024-07-02)
- ERROR Failed to run healthcheck for "rustaceanvim" plugin. Exception:
  .../data/nvim/lazy/rustaceanvim/lua/rustaceanvim/health.lua:104:       cargo-nextest: not found: Could not find an executable binary.
        rustaceanvim requires [cargo-nextest](https://nexte.st).
              Next generation test runner for Rust projects.
        Optional dependency, required if the 'tools.enable_nextest' option is set.
```

My actual config:
```
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 1.81.0-nightly (6292b2a 2024-07-02)
- OK Cargo: found cargo 1.81.0-nightly (4ed7bee47 2024-06-25)
- OK rustc: found rustc 1.81.0-nightly (6292b2af6 2024-07-02)
- OK debug adapter: found codelldb 

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- OK tree-sitter parser for Rust detected.
```

### How to reproduce the issue

`Cargo.toml`:
```toml
[workspace]
members = [ "mylib","t1"]
```

`./mylib/Cargo.toml`:
```toml
[package]
name = "mylib"
version = "0.1.0"
edition = "2021"

[dependencies]
```

`./mylib/src/lib.rs`:
```rs
#![deny(unused)]
pub fn add(left: u64, right: u64) -> u64 {
    let a = 3;
    left + right
}
```

`./t1/Cargo.toml`:
```toml
[package]
name = "t1"
version = "0.1.0"
edition = "2021"

[dependencies]
mylib = { path = "../mylib" }
```

`./t1/src/main.rs`:
```rs
fn main() {
    let a: i32 = "";
    println!("Hello, world!");
}
```

Now open `./t1/src/main.rs` with `nvim` (or `nvim -u minimal.lua`). The erroneous line is not linted. Sanity check: open `./mylib/src/lib.rs`, it lints the unused variable.

I believe it has to do with `rustaceanvim` because it works both with lspconfig's and rust-tools configurations of RA, but not with `rustaceanvim`.

### Expected behaviour

It lints both the unused variable in the dependency AND a type mismatch in the bin project.
![image](https://github.com/user-attachments/assets/2a88bd6b-0b61-46ce-8f57-051f18b97e42)

### Actual behaviour

If there's a clippy error in a dependency, the linting stops there.

![image](https://github.com/user-attachments/assets/495505f6-f20d-4f22-b8c5-34002a2ff731)

It's worth noting that it works as usual if it is not an error, but, for example, a warning:
![image](https://github.com/user-attachments/assets/d72cf5aa-07be-4223-91b7-953aef0a4c57)

### The minimal config used to reproduce this issue.

```Lua
The one suggested by this form reproduces the issue:
https://github.com/mrcjkb/rustaceanvim/blob/master/troubleshooting/minimal.lua
```

**Comment by mrcjkb** [comment]
Hey 👋 

> I believe it has to do with rustaceanvim because it works both with lspconfig's and rust-tools configurations of RA, but not with rustaceanvim.

This is because rustaceanvim enables clippy by default, if it detects that clippy is installed. 
If you don't want that behaviour, you can disable clippy, see `:h rustaceanvim.config`.
