### ISSUE TITLE
Add support for ra-multiplex

### ISSUE THREAD

**Issue by mralj** [mrcjkb/rustaceanvim#631]
Hi!

I cannot figure out how to make rustaceanvim work with [ra-multiplex](https://github.com/pr2502/ra-multiplex), and I'm not sure if something like this is even supported by rustaceanvim.

The way this is set up via regular LSP is as follows:

```LUA
require("lspconfig").rust_analyzer.setup {
  cmd = vim.lsp.rpc.connect("127.0.0.1", 27631),
  -- When using unix domain sockets, use something like:
  --cmd = vim.lsp.rpc.connect("/path/to/ra-multiplex.sock"),
  settings = {
    ["rust-analyzer"] = {
      lspMux = {
        version = "1",
        method = "connect",
        server = "rust-analyzer",
      },
    },
  },
}
```

So I tried to mimic this using rustaceanvim: 

```LUA
local M = {}

M.init = function()
  vim.g.rustaceanvim = {
    server = {
      cmd = vim.lsp.rpc.connect("127.0.0.1", 27631),
      on_attach = function(client, bufnr)
        local lsp_map = function(mode, keys, func, desc)
          vim.keymap.set(mode, keys, func, { buffer = bufnr, desc = desc })
        end
        -- some key mappings here 
      end,
      default_settings = {
        -- rust-analyzer language server configuration
        ["rust-analyzer"] = {
          lspMux = {
            version = "1",
            method = "connect",
            server = "rust-analyzer",
          },
        },
      },
    },
  }
end

return M
```

But no luck; Even syntax isn't highlighted, and this is, I guess because I'm using `vim.lsp.rpc.connect`?
I see in the `ra-multiplex` log that a connection is established, but apart from that, nothing.
The `checkhealth` marks everything as OK. 

My question is, is it possible to use the `ra-multiplex` with `rustaceanvim` at the moment, and if so, how?
And if not, would you consider adding this in the future?

 One of the most obvious benefits is the "startup time," i.e., when I'm working on my project, it takes even a couple of minutes (on my MBP M1 16GB RAM) to get "everything going" (i.e., I get syntax highlighting and output of `cargo check` immediately, but for "show definition" or "go to references" to work, it takes even minutes).

**Comment by mralj** [comment]
@mrcjkb  Wow, this was quick, thank you so much <3

I don't want to bother you with this further, but when I tested it on my machine, it works, but has this strange behaviour.
Whenever I try to switch to a newly opened file I'm greeted with this screen:

![image](https://github.com/user-attachments/assets/de8e3b80-f081-4783-bf34-34a8868a8507)

I've noticed following in output in `ra-multiplex` server:
`[ WARN instance{pid=64414}: server responded with error res={"jsonrpc":"2.0","error":{"code":-32801,"message":"content modified"},"id":"client_id:0:n:8"}`

I haven't noticed this error when using `ra-multiplex` with the LSP.
Here is my whole `rustecaceanvim` config:

```Lua
local M = {}

M.init = function()
  vim.g.rustaceanvim = {
    server = {
      on_attach = function(client, bufnr)
        local lsp_map = function(mode, keys, func, desc)
          vim.keymap.set(mode, keys, func, { buffer = bufnr, desc = desc })
        end

        -- rust-lsp mappings
        lsp_map("n", "K", function()
          vim.cmd.RustLsp { "hover", "actions" }
        end, "Rust hover docs")
        lsp_map("n", "J", function()
          vim.cmd.RustLsp "joinLines"
        end, "Rust join lines")
        lsp_map("n", "<Leader>ca", function()
          vim.cmd.RustLsp "codeAction"
        end, "Rust Code action")
        lsp_map("n", "<Leader>rca", function()
          vim.cmd.RustLsp "explainError"
        end, "Rust error explain")
        lsp_map("n", "<Leader>ree", function()
          vim.cmd.RustLsp "openDocs"
        end, "Rust docs")
        lsp_map("n", "<Leader>rem", function()
          vim.cmd.RustLsp "expandMacro"
        end, "Rust expand macro")

        -- copy from lsp_config
        lsp_map("n", "gd", vim.lsp.buf.definition, "Goto definition")
        lsp_map("n", "gD", vim.lsp.buf.declaration, "Goto declaration")
        lsp_map("n", "gI", vim.lsp.buf.implementation, "Goto implementation")
        lsp_map("n", "go", vim.lsp.buf.type_definition, "Goto type definition")
        lsp_map("n", "gr", vim.lsp.buf.references, "Goto references")
        lsp_map("n", "ra", vim.lsp.buf.rename, "Rename")
      end,
    },
  }
end

return M

```

**Comment by mrcjkb** [comment]
[oops](https://github.com/mrcjkb/rustaceanvim/commit/52a031f600caf53520f2ba1ad9a6055f04c71e79) 😅

> I've noticed following in output in ra-multiplex server:
[ WARN instance{pid=64414}: server responded with error res={"jsonrpc":"2.0","error":{"code":-32801,"message":"content modified"},"id":"client_id:0:n:8"}

I don't think that's anything to worry about. 
It seems to work fine in my tests and it works fine on my end. 

thanks for reminding me about that project btw 🙏
It's pretty cool!

**Comment by mralj** [comment]
> [oops](https://github.com/mrcjkb/rustaceanvim/commit/52a031f600caf53520f2ba1ad9a6055f04c71e79) 😅
Yeah, it happens 🙈

Once again, thank you for jumping on this so quickly it works perfectly now <3
Merry Christmas, if you are celebrating, and if not have a great weekend :)
