### ISSUE TITLE
Extend `dap.configurations.rust` with discovered configurations, then use that in `RustLsp debuggables`

### ISSUE THREAD

**Issue by mrcjkb** [mrcjkb/rustaceanvim#66]
I'm not entirely sure (this was taken over from rust-tools.nvim).
I believe it may be to avoid overriding existing dap `rust` or `lldb` configurations.

Perhaps a better approach to this would be to load `dap.configurations.rust` and to extend it with the discovered configurations, and then to query nvim-dap for configurations to run.
That is [how I do it in haskell-tools.nvim](https://github.com/mrcjkb/haskell-tools.nvim/blob/dc778953e98bf2667424d93dad82eefe319e0f7d/lua/haskell-tools/dap.lua#L144C54-L150C8).

But maybe this is for another PR. I'll create an issue for it :smile:

_Originally posted by @mrcjkb in https://github.com/mrcjkb/rustaceanvim/pull/64#discussion_r1398288289_

**Comment by richchurcher** [comment]
Yeah, this is something I was thinking about in reverse: how to let `:lua require'da'.toggle_breakpoint()` work sensibly in case someone doesn't want to go through the debuggables selection screen. Prior to using these plugins, my approach was just to hit F5 and have the debugger start.

One possibility would be to check for the presence of `dap.configurations.rust`:
- if present, extend it into `dap.configurations.rnm-lldb` (or whatever) to avoid overwriting it
- if absent, attempt to sensibly define `dap.configurations.rust`
- optionally, _also_ define `dap.configurations.rnm-lldb`

The goal being the user doesn't have to care which configuration is used. Another option: allow an override e.g.
```
  use_configuration = 'dap.configurations.rust'
```
