### ISSUE TITLE
Error when i open a file

### ISSUE THREAD

**Issue by GustavoJCL** [mrcjkb/rustaceanvim#9]
### Neovim version (nvim -v)

0.9.4

### Operating system/version

Arch Linux

### Output of `:checkhealth ferris`

rustaceanvim: require("rustaceanvim.health").check()  Checking for Lua dependencies ~ - OK [nvim-lua/plenary.nvim](https://github.com/nvim-lua/plenary.nvim) installed. - OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.  Checking external dependencies ~ - OK rust-analyzer: found rust-analyzer 0.3.1697-standalone - OK Cargo: found cargo 1.73.0 (9c4383fb5 2023-08-26)  Checking config ~ - OK vim.g.rustaceanvim is not set - OK No errors found in config.  Checking for conflicting plugins ~ - ERROR lspconfig.rust_analyzer has been setup. This will likely lead to conflicts with the rustaceanvim LSP client.

### How to reproduce the issue

nvim
open a main.rs file

### Expected behaviour

the file open correctly

### Actual behaviour

`Error opening file: vim/_editor.lua:0: nvim_exec2()..BufReadPost Autocommands for "*": Vim(append):Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:24: Error executing lua: /usr/share/nvim/runtime/filetype.lua:25: nvim_exec2()..BufReadPost Autocommands for "*"..FileType Autocommands for "rust"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[19]..script /home/gus/.local/share/nvim/lazy/rustaceanvim/ftplugin/rust.lua: Vim(runtime):E5113: Error while calling lua chunk: ...al/share/nvim/lazy/rustaceanvim/lua/rustaceanvim/lsp.lua:16: attempt to call field 'joinpath' (a nil value)
stack traceback:
	...al/share/nvim/lazy/rustaceanvim/lua/rustaceanvim/lsp.lua:16: in function 'is_library'
	...al/share/nvim/lazy/rustaceanvim/lua/rustaceanvim/lsp.lua:31: in function 'get_root_dir'
	...al/share/nvim/lazy/rustaceanvim/lua/rustaceanvim/lsp.lua:120: in function 'start'
	...us/.local/share/nvim/lazy/rustaceanvim/ftplugin/rust.lua:34: in main chunk
	[C]: in function 'nvim_exec_autocmds'
	...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:157: in function <...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:156>
	[C]: in function 'xpcall'
	.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:113: in function 'try'
	...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:156: in function 'trigger'
	...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:87: in function <...hare/nvim/lazy/lazy.nvim/lua/lazy/core/handler/event.lua:72>
	[C]: in function 'nvim_cmd'
	/usr/share/nvim/runtime/filetype.lua:25: in function </usr/share/nvim/runtime/filetype.lua:24>
	[C]: in function 'nvim_buf_call'
	/usr/share/nvim/runtime/filetype.lua:24: in function </usr/share/nvim/runtime/filetype.lua:10>
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function <vim/_editor.lua:0>
	[C]: in function 'pcall'
	...hare/nvim/lazy/neo-tree.nvim/lua/neo-tree/utils/init.lua:697: in function 'open_file'
	...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:700: in function 'open'
	...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:731: in function 'open_with_cmd'
	...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:740: in function 'open'
	...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:184: in function <...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:183>
stack traceback:
	[C]: in function 'nvim_cmd'
	/usr/share/nvim/runtime/filetype.lua:25: in function </usr/share/nvim/runtime/filetype.lua:24>
	[C]: in function 'nvim_buf_call'
	/usr/share/nvim/runtime/filetype.lua:24: in function </usr/share/nvim/runtime/filetype.lua:10>
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function <vim/_editor.lua:0>
	[C]: in function 'pcall'
	...hare/nvim/lazy/neo-tree.nvim/lua/neo-tree/utils/init.lua:697: in function 'open_file'
	...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:700: in function 'open'
	...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:731: in function 'open_with_cmd'
	...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:740: in function 'open'
	...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:184: in function <...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:183>
stack traceback:
	[C]: in function 'nvim_buf_call'
	/usr/share/nvim/runtime/filetype.lua:24: in function </usr/share/nvim/runtime/filetype.lua:10>
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function <vim/_editor.lua:0>
	[C]: in function 'pcall'
	...hare/nvim/lazy/neo-tree.nvim/lua/neo-tree/utils/init.lua:697: in function 'open_file'
	...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:700: in function 'open'
	...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:731: in function 'open_with_cmd'
	...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:740: in function 'open'
	...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:184: in function <...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:183>`

![image](https://github.com/mrcjkb/rustaceanvim/assets/93671143/39730793-b66f-4f78-be4c-b7024552300a)

### The minimal config used to reproduce this issue.

`"mrcjkb/rustaceanvim",
    version = "^3",
    ft = { "rust" },`

**Comment by mrcjkb** [comment]
Oops. It looks like `vim.fs.joinpath` is a neovim-nightly feature. I'll fix that...
